# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-23 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0002_auto_20181023_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='Book',
            new_name='book',
        ),
    ]
