# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-24 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0002_auto_20181024_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pending',
        ),
    ]
