# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-23 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0003_auto_20181023_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='error',
            field=models.CharField(blank=True, choices=[(100, 'Unknown error'), (101, 'File type error')], max_length=30, null=True),
        ),
    ]
