# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-24 06:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.contrib.postgres.operations import HStoreExtension
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0004_auto_20181023_1106'),
    ]

    operations = [
        HStoreExtension(),
        migrations.RemoveField(
            model_name='cell',
            name='field',
        ),
        migrations.AddField(
            model_name='sheet',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Cell',
        ),
    ]
