# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0011_sheet_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
