# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0014_merge_20190205_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='meta_status',
        ),
    ]
