# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-18 19:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0015_remove_book_meta_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='data',
        ),
        migrations.AddField(
            model_name='field',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
