# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0028_auto_20180330_0953'),
        ('organization', '0002_auto_20180510_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='country',
        ),
        migrations.AddField(
            model_name='organization',
            name='regions',
            field=models.ManyToManyField(blank=True, to='geo.Region'),
        ),
    ]
