# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-14 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180510_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='donor',
            field=models.BooleanField(default=False),
        ),
    ]
