# Generated by Django 2.1.8 on 2019-04-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20190416_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
