# Generated by Django 2.1.10 on 2019-11-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20190912_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='relief_web_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='relief_web_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
