# Generated by Django 3.2.15 on 2022-11-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organization_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
