# Generated by Django 3.2.15 on 2023-02-02 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_projectchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSHIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Creating'), (1, 'Created')], default=0)),
                ('pickle_version', models.CharField(max_length=10, null=True)),
                ('index_pickle', models.BinaryField(null=True)),
                ('has_errored', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lshindex_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'verbose_name_plural': 'LSH Indices',
            },
        ),
    ]
