# Generated by Django 3.2.15 on 2023-01-20 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0046_auto_20230120_0543'),
        ('project', '0002_projectchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSHIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('created', 'Created')], default='creating', max_length=20)),
                ('pickle_version', models.CharField(max_length=10, null=True)),
                ('index_pickle', models.BinaryField(null=True)),
                ('has_errored', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lshindex_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'verbose_name_plural': 'LSH Indices',
            },
        ),
        migrations.CreateModel(
            name='LeadHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_hash', models.BinaryField()),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadhash_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lead.lead')),
                ('lsh_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deduplication.lshindex')),
            ],
            options={
                'verbose_name_plural': 'Lead Hashes',
                'unique_together': {('lead', 'lsh_index')},
            },
        ),
        migrations.CreateModel(
            name='DeduplicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('calculated', 'Calculated'), ('responded', 'Responded')], default='pending', max_length=15)),
                ('client_id', models.TextField()),
                ('project_id', models.IntegerField()),
                ('lead_id', models.IntegerField()),
                ('callback_url', models.TextField()),
                ('text_extract', models.TextField()),
                ('has_errored', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('result', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deduplicationrequest_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project_id', 'lead_id')},
            },
        ),
    ]
