version: '3.2'

services:
    db:
        image: $DOCKER_DB_IMAGE
        volumes:
            - postgres-data:/var/lib/postgresql/data

    redis:
        image: redis:latest
        volumes:
            - redis-data:/data

    server:
        image: $DOCKER_IMAGE_SERVER
        build: .
        env_file:
            - .env
        command: bash -c '/code/scripts/wait-for-it.sh db:5432 && /code/scripts/run_develop.sh'
        volumes:
            - .:/code
            - media:/media
        ports:
            - '8000:8000'
        depends_on:
            - db
            - redis

volumes:
  media:
  postgres-data:
  redis-data:
