# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-24 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0003_remove_book_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='label',
            new_name='title',
        ),
    ]
