# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-30 07:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0010_remove_sheet_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
