# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 08:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0012_auto_20190107_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
