# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0012_auto_20190107_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.File'),
        ),
    ]
