# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0013_auto_20190131_1019'),
        ('tabular', '0013_auto_20190131_0852'),
    ]

    operations = [
    ]
