# Generated by Django 2.1 on 2019-02-21 05:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0015_remove_book_meta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
