# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 05:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0016_auto_20190218_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
