# Generated by Django 2.1.7 on 2019-03-08 14:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0017_field_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
