# Generated by Django 2.1.7 on 2019-03-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0018_auto_20190308_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('ods', 'ODS')], max_length=30),
        ),
    ]
