# Generated by Django 2.1.8 on 2019-05-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0019_auto_20190313_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='data_row_index',
            field=models.IntegerField(default=0),
        ),
    ]
