# Generated by Django 2.1.8 on 2019-06-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0020_sheet_data_row_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_type',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('xls', 'XLS'), ('ods', 'ODS')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='data_row_index',
            field=models.IntegerField(default=1),
        ),
    ]
