# Generated by Django 2.1.8 on 2019-05-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0020_sheet_data_row_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='data_row_index',
            field=models.IntegerField(default=1),
        ),
    ]
