# Generated by Django 3.2 on 2021-05-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0021_auto_20190611_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='meta',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='options',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='field',
            name='options',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='options',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
