# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 07:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysisframework_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysisframework_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exportable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_id', models.CharField(max_length=100)),
                ('inline', models.BooleanField(default=False)),
                ('analysis_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_framework.AnalysisFramework')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('analysis_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_framework.AnalysisFramework')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('analysis_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_framework.AnalysisFramework')),
            ],
        ),
    ]
