# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportable',
            name='schema_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='filter',
            name='schema_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='widget',
            name='schema_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
