# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0004_filter_filter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='filter_type',
            field=models.CharField(choices=[('number', 'Number'), ('list', 'List')], default='list', max_length=20),
        ),
    ]
