# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0005_auto_20171025_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportable',
            old_name='schema_id',
            new_name='widget_id',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='schema_id',
            new_name='widget_id',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='schema_id',
            new_name='widget_id',
        ),
    ]
