# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0007_widget_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='key',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
