# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0008_auto_20171124_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisframework',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
