# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20171016_0957'),
        ('analysis_framework', '0009_analysisframework_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisframework',
            name='snapshot_one',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_one_framework', to='gallery.File'),
        ),
        migrations.AddField(
            model_name='analysisframework',
            name='snapshot_two',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_two_framework', to='gallery.File'),
        ),
    ]
