# Generated by Django 2.1.9 on 2019-08-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0004_auto_20180912_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMMEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('provider', models.CharField(max_length=60)),
                ('provider_id', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='connector',
            name='source',
            field=models.CharField(choices=[('atom-feed', 'Atom Feed'), ('rss-feed', 'RSS Feed'), ('emm', 'RSS Feed'), ('acaps-briefing-notes', 'ACAPS Briefing Notes'), ('unhcr-portal', 'UNHCR Portal'), ('relief-web', 'ReliefWeb Reports'), ('post-disaster-needs-assessment', 'Post Disaster Needs Assessment'), ('research-resource-center', 'Research Resource Center'), ('world-food-programme', 'WFP Assessments'), ('humanitarian-response', 'Humanitarian Response')], max_length=96),
        ),
        migrations.AlterUniqueTogether(
            name='emmentity',
            unique_together={('name', 'provider', 'provider_id')},
        ),
    ]
