# Generated by Django 2.1.9 on 2019-08-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0005_auto_20190828_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMMConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_separator', models.CharField(default=';', max_length=10)),
                ('trigger_regex', models.CharField(default='(\\((?P<risk_factor>[a-zA-Z ]+)\\)){0,1}(?P<keyword>[a-zA-Z ]+)\\[(?P<count>\\d+)]', max_length=300)),
                ('entity_tag', models.CharField(default='emm:entity', max_length=100)),
                ('trigger_tag', models.CharField(default='category', max_length=50)),
                ('trigger_attribute', models.CharField(default='emm:trigger', max_length=50)),
            ],
        ),
    ]
