# Generated by Django 2.1.9 on 2019-08-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0026_auto_20190828_1055'),
        ('connector', '0006_emmconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EMMEntity',
        ),
    ]
