# Generated by Django 2.1.9 on 2019-08-29 05:38

from django.db import migrations


def create_emm_config(apps, schema_editor):
    EMMConfig = apps.get_model('connector', 'EMMConfig')
    EMMConfig.objects.create()


def remove_emm_config(apps, schema_editor):
    EMMConfig = apps.get_model('connector', 'EMMConfig')
    EMMConfig.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0007_delete_emmentity'),
    ]

    operations = [
        migrations.RunPython(create_emm_config, remove_emm_config),
    ]
