# Generated by Django 2.1.9 on 2019-09-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0008_auto_20190829_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='source',
            field=models.CharField(choices=[('atom-feed', 'Atom Feed'), ('rss-feed', 'RSS Feed'), ('emm', 'European Media Monitor'), ('acaps-briefing-notes', 'ACAPS Briefing Notes'), ('unhcr-portal', 'UNHCR Portal'), ('relief-web', 'ReliefWeb Reports'), ('post-disaster-needs-assessment', 'Post Disaster Needs Assessment'), ('research-resource-center', 'Research Resource Center'), ('world-food-programme', 'WFP Assessments'), ('humanitarian-response', 'Humanitarian Response')], max_length=96),
        ),
    ]
