# Generated by Django 2.1.13 on 2019-11-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0009_auto_20190904_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('broken', 'Broken'), ('working', 'Working')], default='working', max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
