# Generated by Django 2.1.13 on 2019-11-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0011_add_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectorsource',
            name='id',
        ),
        migrations.AlterField(
            model_name='connectorsource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='connectorsource',
            name='key',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
