# Generated by Django 2.1.13 on 2019-11-07 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0012_auto_20191107_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='source_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connector.ConnectorSource'),
        ),
    ]
