# Generated by Django 2.1.13 on 2019-11-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0014_auto_20191107_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='source',
        ),
    ]
