# Generated by Django 2.1.13 on 2019-11-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0016_auto_20191107_0500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectorsource',
            old_name='name',
            new_name='title',
        ),
    ]
