# Generated by Django 3.2 on 2021-05-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0017_auto_20191107_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='params',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
