# Generated by Django 2.1.15 on 2020-09-04 05:57

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0062_auto_20200804_0810'),
        ('connector', '0017_auto_20191107_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure')], max_length=30, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='UnifiedConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unifiedconnector_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unifiedconnector_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnifiedConnectorSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('stats', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('failure', 'Failure')], default='processing', max_length=30)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connector.UnifiedConnector')),
            ],
        ),
        migrations.CreateModel(
            name='UnifiedConnectorSourceLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connector.ConnectorLead')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connector.UnifiedConnectorSource')),
            ],
        ),
        migrations.AddField(
            model_name='unifiedconnectorsource',
            name='leads',
            field=models.ManyToManyField(blank=True, through='connector.UnifiedConnectorSourceLead', to='connector.ConnectorLead'),
        ),
        migrations.AddField(
            model_name='unifiedconnectorsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connector.ConnectorSource'),
        ),
    ]
