# Generated by Django 2.1.15 on 2020-09-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0019_unifiedconnector_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorsource',
            name='logo',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='connector-logo/'),
        ),
        migrations.AddField(
            model_name='unifiedconnectorsourcelead',
            name='already_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unifiedconnectorsourcelead',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unifiedconnectorsource',
            name='status',
            field=models.CharField(choices=[('not_processed', 'Not Processed'), ('processing', 'Processing'), ('success', 'Success'), ('failure', 'Failure')], default='not_processed', max_length=30),
        ),
    ]
