# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0013_auto_20180107_0538'),
        ('deep_migration', '0007_auto_20180114_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_migrated_at', models.DateTimeField(auto_now_add=True)),
                ('last_migrated_at', models.DateTimeField(auto_now=True)),
                ('old_id', models.IntegerField(unique=True)),
                ('lead', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.Lead')),
            ],
            options={
                'abstract': False,
                'ordering': ['-first_migrated_at'],
            },
        ),
    ]
