# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deep_migration', '0010_auto_20180115_0613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalysisFramworkMigration',
            new_name='AnalysisFrameworkMigration',
        ),
    ]
