# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 05:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('xlsx', 'xlsx'), ('docx', 'docx'), ('pdf', 'pdf')], max_length=100)),
                ('type', models.CharField(choices=[('entries', 'entries')], max_length=100)),
                ('file', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='export/')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
