# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-08 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0006_auto_20180707_1206'),
        ('export', '0006_auto_20180706_1021'),
    ]

    operations = [
    ]
