# Generated by Django 2.1.8 on 2019-04-26 08:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0007_merge_20180708_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='export_type',
            field=models.CharField(blank=True, choices=[('excel', 'Excel'), ('report', 'Report'), ('json', 'Json')], max_length=100),
        ),
        migrations.AddField(
            model_name='export',
            name='filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='type',
            field=models.CharField(blank=True, choices=[('entries', 'Entries'), ('assessments', 'Assessments')], max_length=99),
        ),
    ]
