# Generated by Django 2.1.8 on 2019-04-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0008_auto_20190426_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=30),
        ),
    ]
