# Generated by Django 2.1.13 on 2020-01-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0009_export_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='type',
            field=models.CharField(blank=True, choices=[('entries', 'Entries'), ('assessments', 'Assessments'), ('planned_assessments', 'Planned Assessments')], max_length=99),
        ),
    ]
