# Generated by Django 2.1.15 on 2020-12-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0011_export_is_deleted'),
        ('export', '0011_export_is_archived'),
    ]

    operations = [
    ]
