# Generated by Django 2.1.15 on 2021-01-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0012_merge_20201229_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('success', 'Success'), ('failure', 'Failure'), ('canceled', 'Canceled')], default='pending', max_length=30),
        ),
    ]
