# Generated by Django 3.2 on 2021-05-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0012_merge_20201229_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='filters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='export',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('success', 'Success'), ('failure', 'Failure'), ('canceled', 'Canceled')], default='pending', max_length=30),
        ),
    ]
