# Generated by Django 2.1.15 on 2021-04-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0013_auto_20210120_0443'),
        ('export', '0013_auto_20210409_0423'),
    ]

    operations = [
    ]
