# Generated by Django 3.2 on 2021-06-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0013_auto_20210503_0431'),
        ('export', '0014_merge_20210419_0941'),
    ]

    operations = [
    ]
