# Generated by Django 3.2.5 on 2021-11-02 10:04
import copy

from django.db import migrations, models


def update_export_filters_extra_options_fields(apps, _):
    Export = apps.get_model('export', 'Export')
    qs = Export.objects.all()
    print(f'\n\tFound {qs.count()} exports.')
    for index, export in enumerate(qs.all(), start=1):
        if not export.filters:
            continue

        export.extra_options['old_filters_data'] = copy.deepcopy(export.filters)
        export.filters = {}
        export.save(update_fields=('extra_options', 'filters',))
        print(f'\t - Processing {index}', end='\r')


def revert_export_filters_extra_options_fields(apps, _):
    Export = apps.get_model('export', 'Export')
    qs = Export.objects.all()
    print(f'\n\tFound {qs.count()} exports.')
    for index, export in enumerate(qs.all(), start=1):
        if 'old_filters_data' not in export.extra_options:
            continue

        export.filters = export.extra_options['old_filters_data']
        export.save(update_fields=('filters',))
        print(f'\t - Processing {index}', end='\r')


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0016_auto_20211027_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='extra_options',
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(
            update_export_filters_extra_options_fields,
            reverse_code=revert_export_filters_extra_options_fields,
        ),
    ]
