# Generated by Django 3.2.10 on 2022-01-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0017_export_extra_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='export',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
