# Generated by Django 3.2.10 on 2022-05-11 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20210708_0404'),
        ('export', '0018_auto_20220111_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.analysis', verbose_name='analysis'),
        ),
        migrations.AlterField(
            model_name='export',
            name='type',
            field=models.CharField(choices=[('entries', 'Entries'), ('assessments', 'Assessments'), ('planned_assessments', 'Planned Assessments'), ('analyses', 'Analyses')], max_length=99),
        ),
    ]
