# Generated by Django 3.2.15 on 2023-01-05 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import export.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('export', '0020_alter_export_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='pending',
        ),
        migrations.AlterField(
            model_name='export',
            name='file',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to=export.models.export_upload_to),
        ),
        migrations.AlterField(
            model_name='export',
            name='format',
            field=models.CharField(choices=[('csv', 'csv'), ('xlsx', 'xlsx'), ('docx', 'docx'), ('pdf', 'pdf'), ('json', 'json')], max_length=100),
        ),
        migrations.CreateModel(
            name='GenericExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to=export.models.export_upload_to)),
                ('format', models.CharField(choices=[('csv', 'csv'), ('xlsx', 'xlsx'), ('docx', 'docx'), ('pdf', 'pdf'), ('json', 'json')], max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('success', 'Success'), ('failure', 'Failure'), ('canceled', 'Canceled')], default='pending', max_length=30)),
                ('type', models.CharField(choices=[('projects_stats', 'Projects Stats')], max_length=99)),
                ('filters', models.JSONField(default=dict)),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
