# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_group', '0002_auto_20170907_0949'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='permitted_user_groups',
            field=models.ManyToManyField(blank=True, to='user_group.UserGroup'),
        ),
        migrations.AddField(
            model_name='file',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
