# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20171016_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
