# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20171217_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_extract', models.TextField(blank=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gallery.File')),
            ],
        ),
    ]
