# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 08:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20171230_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='filepreview',
            name='extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filepreview',
            name='ngrams',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
