# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-13 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20180507_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='client_id',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, unique=True),
        ),
    ]
