kind: Secret
apiVersion: v1
metadata:
  name: {{ template "the-deep.secretname" . }}
  labels:
    app: {{ include "the-deep.fullname" . }}
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  # Django secret key
  DJANGO_SECRET_KEY: {{ required "secrets.DJANGO_SECRET_KEY" .Values.secrets.DJANGO_SECRET_KEY | quote }}

  # Database
  {{- if .Values.postgresql.enabled }}
  DATABASE_NAME: {{.Values.postgresql.auth.database | quote }}
  DATABASE_USER: {{.Values.postgresql.auth.username | quote }}
  DATABASE_PASSWORD: {{.Values.postgresql.auth.password | quote }}
  DATABASE_PORT: {{ include "postgresql.v1.service.port" .Subcharts.postgresql | quote }}
  DATABASE_HOST: {{ include "postgresql.v1.primary.fullname" .Subcharts.postgresql }}
  {{- else }}
  DATABASE_NAME: {{ required "secrets.DATABASE_NAME" .Values.secrets.DB_NAME | quote }}
  DATABASE_USER: {{ required "secrets.DATABASE_USER" .Values.secrets.DATABASE_USER | quote }}
  DATABASE_PASSWORD: {{ required "secrets.DATABASE_PASSWORD" .Values.secrets.DATABASE_PASSWORD | quote }}
  DATABASE_PORT: {{ required "secrets.DATABASE_PORT" .Values.secrets.DATABASE_PORT | quote }}
  DATABASE_HOST: {{ required "secrets.DATABASE_HOST" .Values.secrets.DATABASE_HOST | quote }}
  {{- end }}

  # Sentry
  SENTRY_DSN: {{ required "secrets.SENTRY_DSN" .Values.secrets.SENTRY_DSN | quote }}

  # Redis
  {{- if .Values.redis.enabled }}
  CELERY_REDIS_URL: "redis://{{ printf "%s-master" (include "common.names.fullname" .Subcharts.redis) }}:6379/0"
  DJANGO_CACHE_REDIS_URL: "redis://{{ printf "%s-master" (include "common.names.fullname" .Subcharts.redis) }}:6379/2"
  TEST_DJANGO_CACHE_REDIS_URL: "redis://{{ printf "%s-master" (include "common.names.fullname" .Subcharts.redis) }}:6379/12"
  {{- else }}
  CELERY_REDIS_URL: {{ required "secrets.CELERY_REDIS_URL" .Values.secrets.CELERY_REDIS_URL | quote }}
  DJANGO_CACHE_REDIS_URL: {{ required "secrets.DJANGO_CACHE_REDIS_URL" .Values.secrets.DJANGO_CACHE_REDIS_URL | quote }}
  TEST_DJANGO_CACHE_REDIS_URL: {{ required "secrets.TEST_DJANGO_CACHE_REDIS_URL" .Values.secrets.TEST_DJANGO_CACHE_REDIS_URL | quote }}
  {{- end }}

  #Email
  SMTP_EMAIL_HOST: {{ required "env.SMTP_EMAIL_HOST" .Values.secrets.SMTP_EMAIL_HOST | quote }}
  SMTP_EMAIL_PORT: {{ required "env.SMTP_EMAIL_PORT" .Values.secrets.SMTP_EMAIL_PORT | quote }}
  SMTP_EMAIL_USERNAME: {{ required "env.SMTP_EMAIL_USERNAME" .Values.secrets.SMTP_EMAIL_USERNAME | quote }}
  SMTP_EMAIL_PASSWORD: {{ required "env.SMTP_EMAIL_PASSWORD" .Values.secrets.SMTP_EMAIL_PASSWORD | quote }}

  # Hcaptcha
  HCAPTCHA_SECRET: {{ required "secrets.HCAPTCHA_SECRET" .Values.secrets.HCAPTCHA_SECRET | quote }}

  # Additional secrets
  {{- range $name, $value := .Values.secretsAdditional }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}