# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-27 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20181130_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_join_request', 'Join project request'), ('project_join_request_abort', 'Join project request abort'), ('project_join_response', 'Join project response')], max_length=48),
        ),
    ]
