# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0002_auto_20180223_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatafield',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'Multiselect')], default='string', max_length=50),
        ),
        migrations.AlterField(
            model_name='methodologyfield',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'Multiselect')], default='string', max_length=50),
        ),
    ]
