# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0009_auto_20180330_0706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssessmentTopic',
            new_name='Sector',
        ),
    ]
