# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0011_auto_20180330_0709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='focus',
            options={'ordering': ['order'], 'verbose_name_plural': 'focuses'},
        ),
    ]
