# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0012_auto_20180330_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='meta_data',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='methodology_data',
            new_name='methodology',
        ),
    ]
