# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-17 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0013_auto_20180405_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreMatrixColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreMatrixPillar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('weight', models.FloatField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.AssessmentTemplate')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreMatrixRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.ScoreMatrixPillar')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreMatrixScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('value', models.IntegerField(default=1)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.ScoreMatrixColumn')),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.ScoreMatrixPillar')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.ScoreMatrixRow')),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='ScorePillar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('weight', models.FloatField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.AssessmentTemplate')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.ScorePillar')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.IntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.AssessmentTemplate')),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.AddField(
            model_name='scorematrixcolumn',
            name='pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.ScoreMatrixPillar'),
        ),
    ]
