# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-17 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0014_auto_20180417_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmenttemplate',
            name='humanitarian_access_constraints_tooltip',
        ),
        migrations.RemoveField(
            model_name='assessmenttemplate',
            name='humanitarian_affected_location_tooltip',
        ),
        migrations.RemoveField(
            model_name='assessmenttemplate',
            name='humanitarian_limited_tooltip',
        ),
        migrations.RemoveField(
            model_name='assessmenttemplate',
            name='humanitarian_priority_issue_tooltip',
        ),
        migrations.RemoveField(
            model_name='assessmenttemplate',
            name='humanitarian_restricted_tooltip',
        ),
        migrations.RemoveField(
            model_name='assessmenttemplate',
            name='sector_affected_tooltip',
        ),
        migrations.RemoveField(
            model_name='assessmenttemplate',
            name='sector_moderate_pin_tooltip',
        ),
        migrations.RemoveField(
            model_name='assessmenttemplate',
            name='sector_pin_tooltip',
        ),
        migrations.RemoveField(
            model_name='assessmenttemplate',
            name='sector_priority_tooltip',
        ),
        migrations.RemoveField(
            model_name='assessmenttemplate',
            name='sector_severe_pin_tooltip',
        ),
        migrations.RemoveField(
            model_name='assessmenttemplate',
            name='sector_specific_need_tooltip',
        ),
    ]
