# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0018_auto_20180510_0903'),
        ('ary', '0023_auto_20180507_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='lead_group',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.LeadGroup'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='lead',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.Lead'),
        ),
    ]
