# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-11 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0024_auto_20180510_0913'),
        ('ary', '0024_auto_20180510_0723'),
    ]

    operations = [
    ]
