# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-24 10:14
from __future__ import unicode_literals

from django.db import migrations


def add_project_id(apps, schema_editor):
    Assessment = apps.get_model('ary', 'Assessment')
    for ary in Assessment.objects.all():
        ary.project = ary.lead.project
        ary.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0028_assessment_project'),
    ]

    operations = [
        migrations.RunPython(add_project_id)
    ]
