# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-27 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0030_auto_20180824_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatafield',
            name='source_type',
            field=models.CharField(blank=True, choices=[('countries', 'Countries'), ('organizations', 'Organizations'), ('donors', 'Donors')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='methodologyfield',
            name='source_type',
            field=models.CharField(blank=True, choices=[('countries', 'Countries'), ('organizations', 'Organizations'), ('donors', 'Donors')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metadatafield',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('daterange', 'Date Range'), ('select', 'Select'), ('multiselect', 'Multiselect')], default='string', max_length=50),
        ),
        migrations.AlterField(
            model_name='methodologyfield',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('daterange', 'Date Range'), ('select', 'Select'), ('multiselect', 'Multiselect')], default='string', max_length=50),
        ),
    ]
