# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-27 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0032_auto_20190125_0911'),
        ('ary', '0032_underlyingfactor'),
    ]

    operations = [
    ]
