# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0033_merge_20190127_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectedlocation',
            options={'ordering': ['order'], 'verbose_name': 'setting facing most humanitarian access issues', 'verbose_name_plural': 'settings facing most humanitarian access issues'},
        ),
        migrations.AlterModelOptions(
            name='priorityissue',
            options={'ordering': ['order'], 'verbose_name': 'priority humanitarian access issue'},
        ),
        migrations.AlterModelOptions(
            name='prioritysector',
            options={'ordering': ['order'], 'verbose_name': 'sector with most unmet need', 'verbose_name_plural': 'sectors with most unmet need'},
        ),
        migrations.AlterModelOptions(
            name='specificneedgroup',
            options={'ordering': ['order'], 'verbose_name': 'priority group with specific need', 'verbose_name_plural': 'priority groups with specific need'},
        ),
        migrations.AlterModelOptions(
            name='underlyingfactor',
            options={'ordering': ['order'], 'verbose_name': 'main sectoral underlying factor'},
        ),
    ]
