# Generated by Django 2.1.8 on 2019-05-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0034_auto_20190210_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatafield',
            name='source_type',
            field=models.CharField(blank=True, choices=[('countries', 'Countries'), ('organizations', 'Organizations')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='methodologyfield',
            name='source_type',
            field=models.CharField(blank=True, choices=[('countries', 'Countries'), ('organizations', 'Organizations')], default=None, max_length=50, null=True),
        ),
    ]
