# Generated by Django 2.1.8 on 2019-06-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0035_auto_20190517_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('text', models.TextField()),
                ('required', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreQuestionnaireSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('method', models.CharField(choices=[('hno', 'HNO'), ('cna', 'CNA')], max_length=10)),
                ('sub_method', models.CharField(choices=[('criteria', 'Criteria'), ('ethos', 'Ethos')], max_length=10)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.AssessmentTemplate')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreQuestionnaireSubSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.ScoreQuestionnaireSector')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scorequestionnaire',
            name='sub_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.ScoreQuestionnaireSubSector'),
        ),
    ]
