# Generated by Django 2.1.8 on 2019-06-18 04:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0036_auto_20190612_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='questionnaire',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
