# Generated by Django 2.1.10 on 2019-11-22 05:02

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import project.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0058_projectarystats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ary', '0037_assessment_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('methodology', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannedassessment_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannedassessment_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(models.Model, project.mixins.ProjectEntityMixin),
        ),
        migrations.AddField(
            model_name='metadatafield',
            name='show_in_planned_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='methodologyfield',
            name='show_in_planned_assessment',
            field=models.BooleanField(default=False),
        ),
    ]
