# Generated by Django 3.2 on 2021-05-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0038_auto_20191122_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='methodology',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='questionnaire',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='score',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='summary',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='metadatafield',
            name='properties',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='methodologyfield',
            name='properties',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='plannedassessment',
            name='metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='plannedassessment',
            name='methodology',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
