# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 07:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis_framework', '0001_initial'),
        ('lead', '0004_auto_20171006_0733'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('excerpt', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='entry-images/%Y/%m/')),
                ('analysis_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_framework.AnalysisFramework')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.Lead')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Entry')),
                ('exportable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_framework.Exportable')),
            ],
        ),
        migrations.CreateModel(
            name='FilterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=None, null=True, size=None)),
                ('number', models.IntegerField(blank=True, default=None, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Entry')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_framework.Filter')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Entry'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_framework.Widget'),
        ),
    ]
