# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-02 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_entry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
