# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-24 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_auto_20180819_1038'),
        ('entry', '0010_entry_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
