# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-24 09:43
from __future__ import unicode_literals

from django.db import migrations


def add_project_id(apps, schema_editor):
    Entry = apps.get_model('entry', 'Entry')
    for entry in Entry.objects.all():
        entry.project = entry.lead.project
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0011_entry_project'),
    ]

    operations = [
        migrations.RunPython(add_project_id)
    ]
