# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-25 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0014_auto_20181025_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('excerpt', 'Excerpt'), ('image', 'Image'), ('dataSeries', 'Data Series')], default='excerpt', max_length=10),
        ),
    ]
