# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0015_auto_20181025_1502'),
        ('entry', '0015_auto_20181031_0602'),
    ]

    operations = [
    ]
