# Generated by Django 2.1.15 on 2021-02-11 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0064_merge_20200917_1003'),
        ('entry', '0028_auto_20200914_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('main_statement', models.TextField(blank=True)),
                ('information_gap', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticalStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('include_in_report', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Analysis')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='AnalyticalStatementEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('analytical_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.AnalyticalStatement')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Entry')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='analyticalstatement',
            name='entries',
            field=models.ManyToManyField(blank=True, through='analysis.AnalyticalStatementEntry', to='entry.Entry'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticalstatemententry',
            unique_together={('entry', 'analytical_statement')},
        ),
    ]
