# Generated by Django 2.1.15 on 2021-04-09 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='analysispillar',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='analysis',
            name='client_id',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysis',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysispillar',
            name='client_id',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='analysispillar',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysispillar_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysispillar',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analysispillar',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysispillar_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticalstatement',
            name='client_id',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='analyticalstatement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyticalstatement',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyticalstatement_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticalstatement',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analyticalstatement',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyticalstatement_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticalstatemententry',
            name='client_id',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='analyticalstatemententry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyticalstatemententry',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyticalstatemententry_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticalstatemententry',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analyticalstatemententry',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyticalstatemententry_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
