# Generated by Django 2.1.15 on 2021-04-30 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20210409_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalstatement',
            name='uuid',
            field=models.CharField(default=uuid.UUID('39ded0bd-fdb3-4e75-9e15-4dd6ca679e73'), max_length=255),
        ),
        migrations.AddField(
            model_name='analyticalstatemententry',
            name='uuid',
            field=models.CharField(default=uuid.UUID('8e54ab18-3a84-4120-ba8b-24890ea50a59'), max_length=255),
        ),
    ]
