# Generated by Django 2.1.15 on 2021-05-18 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0029_auto_20210112_0935'),
        ('analysis', '0002_auto_20210409_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscardedEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('redundant', 'Redundant'), ('too_old', 'Too Old'), ('anecdotal', 'ANECDOTAL'), ('outlier', 'Outlier')], max_length=30)),
                ('analysis_pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.AnalysisPillar')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Entry')),
            ],
        ),
    ]
