# Generated by Django 2.1.15 on 2021-06-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20210519_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysispillar',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticalstatement',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
