# Generated by Django 2.1.15 on 2021-04-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20210430_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticalstatement',
            name='uuid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='analyticalstatemententry',
            name='uuid',
            field=models.CharField(max_length=255),
        ),
    ]
