# Generated by Django 3.2 on 2021-06-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_analysispillar_filters'),
        ('analysis', '0003_auto_20210519_0922'),
    ]

    operations = [
    ]
