# Generated by Django 3.2 on 2021-06-29 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_merge_20210603_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
