# Generated by Django 3.2.10 on 2022-06-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20210708_0404'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analyticalstatemententry',
            unique_together=set(),
        ),
    ]
