# Generated by Django 3.2.17 on 2023-04-04 15:10

import analysis.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectchangelog'),
        ('entry', '0037_merge_20220401_0527'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0007_alter_analyticalstatemententry_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('entries_file', models.FileField(max_length=255, upload_to=analysis.models.entries_file_upload_to)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Success'), (3, 'Failed'), (4, 'Send Failed')], default=0)),
                ('additional_filters', models.JSONField(default=dict)),
                ('analysis_pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysispillar')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topicmodel_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topicmodel_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicModelCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entries', models.ManyToManyField(to='entry.Entry')),
                ('topic_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.topicmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AutomaticSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('entries_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('entries_hash', models.CharField(db_index=True, max_length=256)),
                ('entries_file', models.FileField(max_length=255, upload_to=analysis.models.entries_file_upload_to)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Success'), (3, 'Failed'), (4, 'Send Failed')], default=0)),
                ('summary', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automaticsummary_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automaticsummary_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalyticalStatementNGram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('entries_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('entries_hash', models.CharField(db_index=True, max_length=256)),
                ('entries_file', models.FileField(max_length=255, upload_to=analysis.models.entries_file_upload_to)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Success'), (3, 'Failed'), (4, 'Send Failed')], default=0)),
                ('unigrams', models.JSONField(default=dict)),
                ('bigrams', models.JSONField(default=dict)),
                ('trigrams', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyticalstatementngram_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyticalstatementngram_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
