# Generated by Django 3.2.17 on 2023-04-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_analyticalstatementngram_automaticsummary_topicmodel_topicmodelcluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalstatement',
            name='information_gaps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analyticalstatement',
            name='report_text',
            field=models.TextField(blank=True),
        ),
    ]
