# Generated by Django 3.2.17 on 2023-04-17 08:32

import analysis.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0037_merge_20220401_0527'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_projectchangelog'),
        ('analysis', '0009_auto_20230411_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticalStatementGeoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Success'), (3, 'Failed'), (4, 'Send Failed')], default=0)),
                ('entries_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('entries_hash', models.CharField(db_index=True, max_length=256)),
                ('entries_file', models.FileField(max_length=255, upload_to=analysis.models.entries_file_upload_to)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyticalstatementgeotask_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyticalstatementgeotask_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalyticalStatementGeoEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=list)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.entry')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_geos', to='analysis.analyticalstatementgeotask')),
            ],
        ),
    ]
