# Generated by Django 3.2.17 on 2023-08-23 12:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0012_organization_popularity'),
        ('gallery', '0020_merge_0019_auto_20210120_0443_0019_auto_20210503_0431'),
        ('analysis', '0010_analyticalstatementgeoentry_analyticalstatementgeotask'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('is_public', models.BooleanField(default=False, help_text='A report should be public for "shareable link" to be accessible by')),
                ('slug', models.CharField(db_index=True, help_text='For sharing we use this slug to get the permalink', max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('configuration', models.JSONField(default=dict)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysis')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysisreport_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysisreport_modified', to=settings.AUTH_USER_MODEL)),
                ('organizations', models.ManyToManyField(blank=True, to='organization.Organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisReportContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.SmallIntegerField()),
                ('column', models.SmallIntegerField()),
                ('width', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('height', models.SmallIntegerField(blank=True, null=True)),
                ('style', models.JSONField(default=dict)),
                ('content_type', models.SmallIntegerField(choices=[(1, 'Text'), (2, 'Heading'), (3, 'Image'), (4, 'URL')])),
                ('content_style', models.JSONField(default=dict)),
                ('content_configuration', models.JSONField(default=dict)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisreport')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisReportUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'CSV'), (2, 'XLSX'), (3, 'GeoJson'), (4, 'Image')])),
                ('metadata', models.JSONField(default=dict)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gallery.file')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisreport')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisReportSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('report_data_file', models.FileField(upload_to='analysis_report_snapshot/')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysisreportsnapshot_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysisreportsnapshot_modified', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisreport')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisReportContainerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisreportcontainer')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.analysisreportupload')),
            ],
        ),
    ]
