# Generated by Django 3.2.17 on 2023-08-30 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_analysisreport_analysisreportcontainer_analysisreportcontainerdata_analysisreportsnapshot_analysisre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisreportcontainer',
            name='content_style',
        ),
    ]
