# Generated by Django 3.2.25 on 2024-04-26 09:14

from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# analysis.migrations.0015_analysisreportcontainerdata_client_reference_id

class Migration(migrations.Migration):

    replaces = [
        ('analysis', '0013_alter_analysisreportcontainer_content_type'),
        ('analysis', '0014_alter_analysisreportcontainer_content_type'),
        ('analysis', '0015_analysisreportcontainerdata_client_reference_id'),
        ('analysis', '0016_alter_analysisreportcontainer_content_type'),
        ('analysis', '0013_auto_20240315_0501'),
        ('analysis', '0017_merge_20240318_0519'),
    ]

    dependencies = [
        ('analysis', '0012_remove_analysisreportcontainer_content_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreportcontainer',
            name='content_type',
            field=models.SmallIntegerField(choices=[(1, 'Text'), (2, 'Heading'), (3, 'Image'), (4, 'URL'), (5, 'Timeline Chart'), (6, 'KPIs'), (7, 'Bar Chart')]),
        ),
        migrations.AlterField(
            model_name='analysisreportcontainer',
            name='content_type',
            field=models.SmallIntegerField(choices=[(1, 'Text'), (2, 'Heading'), (3, 'Image'), (4, 'URL'), (5, 'Timeline Chart'), (6, 'KPIs'), (7, 'Bar Chart'), (8, 'Map')]),
        ),
        migrations.AddField(
            model_name='analysisreportcontainerdata',
            name='client_reference_id',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysisreportcontainer',
            name='content_type',
            field=models.SmallIntegerField(choices=[(1, 'Text'), (2, 'Heading'), (3, 'Image'), (4, 'URL'), (5, 'Timeline Chart'), (6, 'KPIs'), (7, 'Bar Chart'), (8, 'Map'), (9, 'Line Chart')]),
        ),
        migrations.AddField(
            model_name='analyticalstatement',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='topicmodelcluster',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
