# Generated by Django 3.2.17 on 2024-03-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_topicmodelcluster_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalstatement',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
