# Generated by Django 3.2.17 on 2024-03-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_analysisreportcontainerdata_client_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreportcontainer',
            name='content_type',
            field=models.SmallIntegerField(choices=[(1, 'Text'), (2, 'Heading'), (3, 'Image'), (4, 'URL'), (5, 'Timeline Chart'), (6, 'KPIs'), (7, 'Bar Chart'), (8, 'Map'), (9, 'Line Chart')]),
        ),
    ]
