# Generated by Django 3.2.17 on 2024-03-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_auto_20240315_0501'),
        ('analysis', '0016_alter_analysisreportcontainer_content_type'),
    ]

    operations = [
    ]
