# Generated by Django 3.2.25 on 2024-07-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_auto_20240716_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticsummary',
            name='analytical_statement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='automaticsummary',
            name='information_gap',
            field=models.TextField(),
        ),
    ]
