# Generated by Django 3.2.25 on 2024-07-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_auto_20240709_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticalstatement',
            name='is_information_gaps_nlp_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyticalstatement',
            name='is_statement_nlp_triggered',
            field=models.BooleanField(default=False),
        ),
    ]
