# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-13 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='client_id',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='source',
            field=models.CharField(choices=[('rss-feed', 'RSS Feed'), ('unhcr-portal', 'UNHCR Portal'), ('acaps-briefing-notes', 'ACAPS Briefing Notes')], max_length=96),
        ),
    ]
