# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-01 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0002_auto_20180713_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='source',
            field=models.CharField(choices=[('relief-web', 'ReliefWeb Reports'), ('acaps-briefing-notes', 'ACAPS Briefing Notes'), ('rss-feed', 'RSS Feed'), ('unhcr-portal', 'UNHCR Portal')], max_length=96),
        ),
    ]
