# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-11 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0003_auto_20180802_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='source',
            field=models.CharField(choices=[('rss-feed', 'RSS Feed'), ('acaps-briefing-notes', 'ACAPS Briefing Notes'), ('unhcr-portal', 'UNHCR Portal'), ('relief-web', 'ReliefWeb Reports'), ('post-disaster-needs-assessment', 'Post Disaster Needs Assessment'), ('research-resource-center', 'Research Resource Center'), ('world-food-programme', 'WFP Assessments'), ('humanitarian-response', 'Humanitarian Response')], max_length=96),
        ),
    ]
