# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-24 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0004_auto_20181005_0539'),
        ('connector', '0004_auto_20181011_0631'),
    ]

    operations = [
    ]
