# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_last_active_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
