# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20180308_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en-us', 'English (US)'), ('np', 'Nepali')], default='en-us', max_length=255),
        ),
    ]
