# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-01 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_email',
            field=models.BooleanField(default=True),
        ),
    ]
