# Generated by Django 2.1 on 2019-02-21 05:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190212_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_opt_outs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('join_requests', 'Project join requests'), ('news_and_updates', 'News and updates')], max_length=128), blank=True, default=list, size=None),
        ),
    ]
