# Generated by Django 2.1.8 on 2019-04-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20190221_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invalid_email',
            field=models.BooleanField(default=False, help_text='Flagged as bounce email'),
        ),
    ]
