# Generated by Django 2.1.8 on 2019-06-24 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0016_profile_invalid_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('domain_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('private_project', 'Private projects'), ('lead_grid_view', 'Lead grid view'), ('tabular', 'Tabular'), ('zoomable_image', 'Zoomable image')], max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('feature_type', models.CharField(choices=[('released', 'Released'), ('experimental', 'Experimental'), ('early_access', 'Early access')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_domains', models.ManyToManyField(blank=True, to='user.EmailDomain')),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Feature')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
