# Generated by Django 2.1.8 on 2019-06-21 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_emaildomain_feature_featureaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureaccess',
            name='email_domians',
            field=models.ManyToManyField(blank=True, to='user.EmailDomain'),
        ),
        migrations.AlterField(
            model_name='featureaccess',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
