# Generated by Django 2.1.7 on 2019-06-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_emaildomain_feature_featureaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_early_access',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_experimental',
        ),
    ]
