# Generated by Django 2.1.8 on 2019-06-21 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20190621_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureaccess',
            name='feature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Feature'),
        ),
    ]
