# Generated by Django 2.1.8 on 2019-06-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20190621_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureaccess',
            old_name='email_domians',
            new_name='email_domains',
        ),
    ]
