# Generated by Django 2.1.8 on 2019-06-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20190626_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_type',
            field=models.CharField(choices=[('general_access', 'General access'), ('experimental', 'Experimental'), ('early_access', 'Early access')], default='general_access', max_length=128),
        ),
    ]
