# Generated by Django 2.1.10 on 2019-11-11 12:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_static', '0001_initial'),
        ('otp_email', '0001_initial'),
        ('otp_totp', '0002_auto_20190420_0723'),
        ('user', '0020_auto_20190626_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP_Email',
            fields=[
            ],
            options={
                'verbose_name': 'OTP  Email',
                'verbose_name_plural': 'OTP  Emails',
                'proxy': True,
                'indexes': [],
            },
            bases=('otp_email.emaildevice',),
        ),
        migrations.CreateModel(
            name='OTP_Static',
            fields=[
            ],
            options={
                'verbose_name': 'OTP  Static',
                'verbose_name_plural': 'OTP  Statics',
                'proxy': True,
                'indexes': [],
            },
            bases=('otp_static.staticdevice',),
        ),
        migrations.CreateModel(
            name='OTP_TOTP',
            fields=[
            ],
            options={
                'verbose_name': 'OTP TOTP',
                'verbose_name_plural': 'OTP TOTPs',
                'proxy': True,
                'indexes': [],
            },
            bases=('otp_totp.totpdevice',),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_opt_outs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('join_requests', 'Project join requests'), ('news_and_updates', 'News and updates'), ('email_comment', 'Entry comment updates')], max_length=128), blank=True, default=list, size=None),
        ),
    ]
