# Generated by Django 2.1.10 on 2020-01-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20191217_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='key',
            field=models.CharField(choices=[('private_project', 'Private projects'), ('tabular', 'Tabular'), ('zoomable_image', 'Zoomable image'), ('polygon_support_geo', 'Polygon support geo'), ('entry_visualization_configuration', 'Entry visualization configuration')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en-us', 'English (US)'), ('es-ES', 'Spanish'), ('np', 'Nepali')], default='en-us', max_length=255),
        ),
    ]
