# Generated by Django 2.1.15 on 2021-01-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20200120_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='is_available_for_all',
            field=models.BooleanField(default=False),
        ),
    ]
