# Generated by Django 3.2.5 on 2021-08-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_feature_is_available_for_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='key',
            field=models.CharField(choices=[('private_project', 'Private projects'), ('tabular', 'Tabular'), ('zoomable_image', 'Zoomable image'), ('polygon_support_geo', 'Polygon support geo'), ('entry_visualization_configuration', 'Entry visualization configuration'), ('quality_control', 'Quality Control (Deprecated)'), ('new_ui', 'New UI (Deprecated)'), ('analysis', 'Analysis (Deprecated)')], max_length=255, unique=True),
        ),
    ]
