# Generated by Django 3.2.10 on 2022-03-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_feature_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='key',
            field=models.CharField(choices=[('private_project', 'Private projects'), ('tabular', 'Tabular'), ('zoomable_image', 'Zoomable image'), ('polygon_support_geo', 'Polygon support geo'), ('entry_visualization_configuration', 'Entry visualization configuration'), ('connectors', 'Unified Connectors'), ('quality_control', 'Quality Control (Deprecated)'), ('new_ui', 'New UI (Deprecated)'), ('analysis', 'Analysis (Deprecated)'), ('questionnaire', 'Questionnaire Builder')], max_length=255, unique=True),
        ),
    ]
