# Generated by Django 3.2.17 on 2023-07-31 14:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0006_auto_20230719_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreanalyticaldensity',
            name='value',
        ),
        migrations.AddField(
            model_name='scoreanalyticaldensity',
            name='analysis_level_covered',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Issues/unmet needs are detailed'), (1, 'Issues/unmet needs are priotized/ranked'), (2, 'Causes or underlying mechanisms behind issues/unmet needs are detailed'), (3, 'Causes or underlying mechanisms behind issues/unmet needs are priotized/ranked'), (4, 'Severity of some/all issues/unmet_needs_is_detailed'), (5, 'Future issues/unmet needs are detailed'), (6, 'Future issues/unmet needs are priotized/ranked'), (7, 'Severity of some/all future issues/unmet_needs_is_detailed'), (8, 'Recommnedations/interventions are detailed'), (9, 'Recommnedations/interventions are priotized/ranked')]), default=list, size=None),
        ),
        migrations.AddField(
            model_name='scoreanalyticaldensity',
            name='figure_provided',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Total population in the assessed areas'), (1, 'Total population exposed to the shock/event'), (2, 'Total populaiton affected/living in the affected area'), (3, 'Total population facing humanitarian access constraints'), (4, 'Total populaiton in need'), (5, 'Total population in critical need'), (6, 'Total population in severe need'), (7, 'Total population in moderate need'), (9, 'Total population at risk/vulnerable'), (10, 'Total population reached by assistance')]), default=list, size=None),
        ),
    ]
