# Generated by Django 3.2.17 on 2023-07-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0006_auto_20230719_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldocument',
            name='external_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
