# Generated by Django 3.2.17 on 2023-07-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0007_alter_additionaldocument_external_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentregistry',
            name='locations',
        ),
    ]
