# Generated by Django 3.2.17 on 2023-07-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0041_geoarea_centroid'),
        ('assessment_registry', '0008_remove_assessmentregistry_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentregistry',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='focus_location_assessment_reg', to='geo.GeoArea'),
        ),
    ]
