# Generated by Django 3.2.17 on 2023-08-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0007_auto_20230731_1422'),
        ('assessment_registry', '0011_remove_additionaldocument_file_path'),
    ]

    operations = [
    ]
