# Generated by Django 3.2.17 on 2023-08-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0014_alter_scorerating_score_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summaryissue',
            old_name='focus_sub_sector',
            new_name='sub_dimmension',
        ),
        migrations.RenameField(
            model_name='summaryissue',
            old_name='sub_sector',
            new_name='sub_pillar',
        ),
    ]
