# Generated by Django 3.2.17 on 2023-08-03 10:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0015_auto_20230803_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentregistry',
            name='protection_info_mgmts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Protection Monitoring'), (1, 'Protection Needs Assessment'), (2, 'Case Management'), (3, 'Population Data'), (4, 'Protection Response M&E'), (5, 'Communicating with(in) Affected Communities'), (6, 'Security & Situational Awareness'), (7, 'Sectoral System/Other')]), blank=True, null=True, size=None),
        ),
    ]
