# Generated by Django 3.2.17 on 2023-08-04 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0018_scoreanalyticaldensity_figure_provided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarysubdimmensionissue',
            name='order',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summarysubpillarissue',
            name='order',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
