# Generated by Django 3.2.17 on 2023-08-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0019_auto_20230804_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summaryfocus',
            options={'verbose_name': 'SummaryDimmension'},
        ),
    ]
