# Generated by Django 3.2.17 on 2023-08-10 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0024_alter_summary_assessment_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryfocus',
            name='focus',
            field=models.IntegerField(choices=[(100, 'Food Security'), (1, 'Heath'), (2, 'Shelter'), (3, 'Wash'), (4, 'Protection'), (5, 'Nutrition'), (6, 'Livelihood'), (7, 'Education'), (8, 'Logistics'), (9, 'Inter/Cross Sector')]),
            preserve_default=False,
        ),
    ]
