# Generated by Django 3.2.17 on 2023-08-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0025_summaryfocus_focus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentregistry',
            name='donors',
        ),
        migrations.RemoveField(
            model_name='assessmentregistry',
            name='governments',
        ),
        migrations.RemoveField(
            model_name='assessmentregistry',
            name='international_partners',
        ),
        migrations.RemoveField(
            model_name='assessmentregistry',
            name='lead_organizations',
        ),
        migrations.RemoveField(
            model_name='assessmentregistry',
            name='national_partners',
        ),
    ]
