# Generated by Django 3.2.17 on 2023-08-11 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_organization_popularity'),
        ('assessment_registry', '0026_auto_20230811_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRegistryOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_type', models.CharField(choices=[(1, 'Lead Organization'), (2, 'International Partner'), (3, 'National Partner'), (4, 'Donor'), (5, 'Government')], max_length=30)),
                ('assessment_registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_registry.assessmentregistry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'unique_together': {('assessment_registry', 'organization_type', 'organization')},
            },
        ),
        migrations.AddField(
            model_name='assessmentregistry',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, through='assessment_registry.AssessmentRegistryOrganization', to='organization.Organization'),
        ),
    ]
