# Generated by Django 3.2.17 on 2023-08-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_organization_popularity'),
        ('assessment_registry', '0027_auto_20230811_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentregistry',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='assessment_registry_stakeholders', through='assessment_registry.AssessmentRegistryOrganization', to='organization.Organization'),
        ),
    ]
