# Generated by Django 3.2.17 on 2023-08-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_organization_popularity'),
        ('assessment_registry', '0028_alter_assessmentregistry_stakeholders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentregistry',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, through='assessment_registry.AssessmentRegistryOrganization', to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='assessmentregistryorganization',
            name='organization_type',
            field=models.IntegerField(choices=[(1, 'Lead Organization'), (2, 'International Partner'), (3, 'National Partner'), (4, 'Donor'), (5, 'Government')]),
        ),
    ]
