# Generated by Django 3.2.17 on 2023-08-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0030_auto_20230817_0446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summaryfocus',
            options={'verbose_name': 'SummaryDimension'},
        ),
        migrations.AddField(
            model_name='assessmentregistry',
            name='additional_document_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentregistry',
            name='cna_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentregistry',
            name='focus_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentregistry',
            name='metadata_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentregistry',
            name='methodology_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentregistry',
            name='score_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentregistry',
            name='summary_complete',
            field=models.BooleanField(default=False),
        ),
    ]
