# Generated by Django 3.2.17 on 2023-08-23 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment_registry', '0031_auto_20230823_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarySubDimensionIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('focus', models.IntegerField(choices=[(1, 'Food Security'), (2, 'Heath'), (3, 'Shelter'), (4, 'Wash'), (5, 'Protection'), (6, 'Nutrition'), (7, 'Livelihood'), (8, 'Education'), (9, 'Logistics'), (10, 'Inter/Cross Sector')])),
                ('text', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('lead_preview_text_ref', models.JSONField(blank=True, default=None, null=True)),
                ('assessment_registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_focus_subsector_issue_ary', to='assessment_registry.assessmentregistry')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summarysubdimensionissue_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summarysubdimensionissue_modified', to=settings.AUTH_USER_MODEL)),
                ('summary_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_focus_subsector_issue', to='assessment_registry.summaryissue')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SummarySubDimmensionIssue',
        ),
    ]
