# Generated by Django 3.2.17 on 2023-08-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0033_rename_sub_dimmension_summaryissue_sub_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarysubdimensionissue',
            name='sector',
            field=models.IntegerField(choices=[(1, 'Food Security'), (2, 'Heath'), (3, 'Shelter'), (4, 'Wash'), (5, 'Protection'), (6, 'Nutrition'), (7, 'Livelihood'), (8, 'Education'), (9, 'Logistics'), (10, 'Inter/Cross Sector')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summarysubdimensionissue',
            name='focus',
            field=models.IntegerField(choices=[(1, 'Context'), (2, 'Shock/Event'), (3, 'Displacement'), (4, 'Casualties'), (5, 'Information and Communication'), (6, 'Humaniterian Access'), (7, 'Impact'), (8, 'Humanitarian Conditions'), (9, 'People at risk'), (10, 'Priorities & Preferences'), (11, 'Response and Capacities')]),
        ),
    ]
