# Generated by Django 3.2.17 on 2023-08-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0034_auto_20230825_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarysubdimensionissue',
            name='focus',
        ),
    ]
