# Generated by Django 3.2.17 on 2023-08-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0035_remove_summarysubdimensionissue_focus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summaryfocus',
            old_name='focus',
            new_name='sector',
        ),
    ]
