# Generated by Django 3.2.17 on 2023-10-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0039_auto_20231005_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreanalyticaldensity',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
