# Generated by Django 3.2.17 on 2023-10-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0040_scoreanalyticaldensity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerating',
            name='score_type',
            field=models.IntegerField(choices=[(1, 'Relevance'), (2, 'Comprehensiveness'), (3, 'Timeliness'), (4, 'Granularity'), (5, 'Comparability'), (6, 'Source reliability'), (7, 'Methods'), (8, 'Triangulation'), (9, 'Plausibility'), (10, 'Inclusiveness'), (11, 'Assumptions'), (12, 'Corroboration'), (13, 'Structured Analytical Techniques'), (14, 'Consensus'), (15, 'Reproducibility'), (16, 'Clearly Articulated Results'), (17, 'Levels Of Confidence'), (18, 'Illustrations'), (19, 'Sourced data and evidence'), (20, 'Clearly stated outliers')]),
        ),
    ]
