# Generated by Django 3.2.17 on 2023-12-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0044_auto_20231221_0508'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentregistryorganization',
            unique_together=set(),
        ),
    ]
