# Generated by Django 3.2.17 on 2024-01-02 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0049_auto_20231121_0926_squashed_0054_auto_20231218_0552'),
        ('assessment_registry', '0045_auto_20231227_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentregistry',
            name='lead',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.lead'),
        ),
    ]
