# Generated by Django 3.2.17 on 2024-02-13 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0049_auto_20231121_0926_squashed_0054_auto_20231218_0552'),
        ('assessment_registry', '0046_alter_assessmentregistry_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentregistry',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lead.lead'),
        ),
    ]
