# Generated by Django 3.2.17 on 2024-02-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0047_alter_assessmentregistry_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentregistry',
            name='status',
            field=models.IntegerField(choices=[(1, 'Planned'), (2, 'Ongoing'), (3, 'Finalized')], default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summaryissue',
            name='sub_dimension',
            field=models.IntegerField(blank=True, choices=[(1, 'Drivers'), (2, 'Impact on people'), (3, 'Impact on System, Network and services'), (4, 'Living standards'), (5, 'Coping mechanisms'), (6, 'Physical and Mental well being'), (7, 'Needs (by population)'), (8, 'Needs (by humanitarians)'), (9, 'Interventions (by population)'), (10, 'Interventions (by humanitarians)'), (11, 'Demographic Groups'), (12, 'Groups with Specific Needs'), (13, 'Geographical areas'), (14, 'People at risk'), (15, 'Focal issues')], null=True),
        ),
        migrations.AlterField(
            model_name='summaryissue',
            name='sub_pillar',
            field=models.IntegerField(blank=True, choices=[(1, 'Politics'), (2, 'Demography'), (3, 'Socio-cultural'), (4, 'Environment'), (5, 'Security & Stability'), (6, 'Economics'), (7, 'Characteristics'), (8, 'Drivers and Aggravating Factors'), (9, 'Mitigating factors'), (10, 'Hazards & Threats'), (11, 'Characteristics'), (12, 'Push factors'), (13, 'Pull factors'), (14, 'Intentions'), (15, 'Local Integrations'), (16, 'Source & Means'), (17, 'Challenges & Barriers'), (18, 'Knowledge & Info Gaps (by humanitarians)'), (19, 'Knowledge & Info Gaps (by population)'), (20, 'Population to Relief'), (21, 'Relief to Population')], null=True),
        ),
    ]
