# Generated by Django 3.2.17 on 2024-03-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_registry', '0049_assessmentregistry_protection_risks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreanalyticaldensity',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
