# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0002_auto_20171228_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='mime_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
