# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_category_editor'),
        ('export', '0003_export_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
