# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0004_auto_20180116_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='format',
            field=models.CharField(blank=True, choices=[('xlsx', 'xlsx'), ('docx', 'docx'), ('pdf', 'pdf'), ('json', 'json')], max_length=100),
        ),
    ]
