# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-07 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0005_auto_20180227_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='type',
            field=models.CharField(blank=True, choices=[('entries', 'Entries'), ('assessments', 'Assessments')], max_length=100),
        ),
    ]
