# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_lead_classified_doc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='classified_doc_id',
        ),
        migrations.AddField(
            model_name='leadpreview',
            name='classified_doc_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
