# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0014_auto_20180114_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
