# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-25 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0005_auto_20181025_0634'),
        ('lead', '0019_auto_20180713_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='tabular_book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabular.Book'),
        ),
    ]
