# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-28 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0020_lead_tabular_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='tabular_book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tabular.Book'),
        ),
    ]
