# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-10 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0021_auto_20180928_0753'),
        ('lead', '0021_auto_20181228_0942'),
    ]

    operations = [
    ]
