# Generated by Django 2.1.10 on 2019-08-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0023_merge_20190205_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
