# Generated by Django 2.1.11 on 2019-09-12 04:20

from django.db import migrations, models


def forward_merge_restricted_and_protected(apps, schema_editor):
    Lead = apps.get_model('lead', 'Lead')
    Lead.objects.filter(
        models.Q(confidentiality='restricted') |
        models.Q(confidentiality='protected')
    ).update(confidentiality='confidential')


def backward_do_nothing_just_for_compatibility(apps, schema_editor):
    # Since the forward migration merges two values into one,
    # and they are not stored in other fields, data is lost.
    # In this case, while reverting do nothing
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0024_lead_author'),
    ]

    operations = [
        migrations.RunPython(
            forward_merge_restricted_and_protected,
            backward_do_nothing_just_for_compatibility,
        ),
    ]
