# Generated by Django 2.1.9 on 2019-08-28 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0005_auto_20190828_0947'),
        ('lead', '0024_lead_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEMMTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emm_keyword', models.CharField(max_length=100)),
                ('emm_risk_factor', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='emm_entities',
            field=models.ManyToManyField(blank=True, to='connector.EMMEntity'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_type',
            field=models.CharField(choices=[('text', 'Text'), ('disk', 'Disk'), ('website', 'Website'), ('dropbox', 'Dropbox'), ('google-drive', 'Google Drive'), ('rss', 'RSS Feed'), ('emm', 'EMM'), ('api', 'Web API'), ('unknown', 'Unknown')], default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='leademmtrigger',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emm_triggers', to='lead.Lead'),
        ),
    ]
