# Generated by Django 2.1.9 on 2019-08-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0005_auto_20190826_1058'),
        ('lead', '0024_lead_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEMMTriggerCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('emm_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_leads', to='connector.EMMTriggerKeyword')),
                ('emm_risk_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_leads', to='connector.EMMTriggerRiskFactor')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='emm_entities',
            field=models.ManyToManyField(blank=True, to='connector.EMMEntity'),
        ),
        migrations.AddField(
            model_name='leademmtriggercount',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emm_triggers', to='lead.Lead'),
        ),
    ]
