# Generated by Django 2.1.9 on 2019-08-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0025_auto_20190828_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMMEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('provider', models.CharField(max_length=60)),
                ('provider_id', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='emm_entities',
            field=models.ManyToManyField(blank=True, to='lead.EMMEntity'),
        ),
        migrations.AlterUniqueTogether(
            name='emmentity',
            unique_together={('name', 'provider', 'provider_id')},
        ),
    ]
