# Generated by Django 2.1.11 on 2019-09-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0025_auto_20190912_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confidentiality',
            field=models.CharField(choices=[('unprotected', 'Unprotected'), ('confidential', 'Confidential')], default='unprotected', max_length=30),
        ),
    ]
