# Generated by Django 2.1.9 on 2019-09-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0026_auto_20190828_1055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emmentity',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='emmentity',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='emmentity',
            name='provider_id',
        ),
    ]
