# Generated by Django 2.1.11 on 2019-09-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0026_auto_20190906_0927'),
        ('lead', '0026_auto_20190912_0446'),
    ]

    operations = [
    ]
