# Generated by Django 2.1.10 on 2019-09-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0025_auto_20190828_0949'),
        ('lead', '0028_auto_20190912_0446'),
    ]

    operations = [
    ]
