# Generated by Django 2.1.13 on 2019-11-18 14:38

from django.db import migrations, models


def update_classified_preview_status(apps, schema_editor):
    LeadPreview = apps.get_model('lead', 'LeadPreview')
    LeadPreview.objects.filter(~models.Q(classified_doc_id=None)).update(
        classification_status='completed'  # Can't use variable/attribute from within the class here
    )

def update_preview_status_to_none(apps, schema_editor):
    LeadPreview = apps.get_model('lead', 'LeadPreview')
    LeadPreview.objects.update(classification_status='none')


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0030_auto_20191118_1046'),
    ]

    operations = [
        migrations.RunPython(update_classified_preview_status, update_preview_status_to_none),
    ]
