# Generated by Django 2.1.15 on 2020-06-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20191111_0845'),
        ('lead', '0031_auto_20191118_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='authors',
            field=models.ManyToManyField(blank=True, to='organization.Organization'),
        ),
    ]
