# Generated by Django 2.1.15 on 2020-07-15 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0032_lead_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_by_author', to='organization.Organization', verbose_name='author (legacy)'),
        ),
    ]
