# Generated by Django 2.1.15 on 2020-07-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0033_auto_20200715_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=30),
        ),
    ]
