# Generated by Django 2.1.15 on 2020-10-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0034_lead_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadpreview',
            name='file_size',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
