# Generated by Django 2.1.15 on 2020-12-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0034_lead_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('validated', 'Validated')], default='pending', max_length=30),
        ),
    ]
