# Generated by Django 3.2 on 2021-07-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0035_auto_20201204_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_assessment_lead',
            field=models.BooleanField(default=False),
        ),
    ]
