# Generated by Django 3.2 on 2021-07-15 04:32

from django.db import migrations


def set_lead_is_assessment_(Lead, Assessment):
    assessments = Assessment.objects.all()
    leads = Lead.objects.filter(
        assessment__in=assessments
    )
    for lead in leads:
        lead.is_assessment_lead = True
        lead.save(update_fields=['is_assessment_lead'])


def set_lead_is_assessment(apps, schema_editor):
    Lead = apps.get_model('lead', 'Lead')
    Assessment = apps.get_model('ary', 'Assessment')
    set_lead_is_assessment_(Lead, Assessment)


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0036_lead_is_assessment_lead'),
    ]

    operations = [
        migrations.RunPython(
            set_lead_is_assessment,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
