# Generated by Django 3.2.10 on 2022-04-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0038_lead_extraction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='website',
        ),
    ]
