# Generated by Django 3.2.12 on 2022-05-12 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0039_remove_lead_website'),
        ('lead', '0040_alter_lead_confidentiality'),
    ]

    operations = [
    ]
