# Generated by Django 3.2.15 on 2022-12-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0044_usersavedleadfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='duplicate_leads',
            field=models.ManyToManyField(blank=True, related_name='duplicate_of', to='lead.Lead'),
        ),
    ]
