# Generated by Django 3.2.15 on 2023-01-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0045_lead_duplicate_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_indexed',
            field=models.BooleanField(default=False),
        ),
    ]
