# Generated by Django 3.2.15 on 2023-02-27 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0047_auto_20230227_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDuplicates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('source_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.lead')),
                ('target_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_of', to='lead.lead')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='duplicate_leads',
            field=models.ManyToManyField(blank=True, through='lead.LeadDuplicates', to='lead.Lead'),
        ),
    ]
