# Generated by Django 3.2.17 on 2023-12-21 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('lead', '0049_auto_20231121_0926'), ('lead', '0050_delete_extractedlead'), ('lead', '0051_auto_20231128_0958'), ('lead', '0052_auto_20231130_0615'), ('lead', '0053_alter_lead_auto_entry_extraction_status'), ('lead', '0054_auto_20231218_0552')]

    dependencies = [
        ('lead', '0048_auto_20230228_0810'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='auto_entry_extraction_status',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Started'), (2, 'Pending'), (3, 'Success'), (4, 'Failed')], default=0),
        ),
        migrations.AddField(
            model_name='leadpreview',
            name='entry_extraction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadpreview',
            name='text_extraction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
