# Generated by Django 3.2.17 on 2023-11-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0049_auto_20231121_0926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtractedLead',
        ),
    ]
