# Generated by Django 3.2.25 on 2024-06-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0049_auto_20231121_0926_squashed_0054_auto_20231218_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadpreviewimage',
            name='file',
            field=models.FileField(upload_to='lead-preview/attachments/')
        ),
        migrations.RenameModel(
            old_name='LeadPreviewImage',
            new_name='LeadPreviewAttachment'
        ),

        migrations.AddField(
            model_name='leadpreviewattachment',
            name='file_preview',
            field=models.FileField(upload_to='lead-preview/attachments-preview/', null=True)
        ),
    ]
