# Generated by Django 3.2.25 on 2024-06-06 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0049_auto_20231121_0926_squashed_0054_auto_20231218_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPreviewAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('page_number', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('XLSX', 'XLSX'), ('image', 'Image')], max_length=20)),
                ('file', models.FileField(upload_to='lead-preview/attachments/')),
                ('file_preview', models.FileField(upload_to='lead-preview/attachments-preview/')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lead.lead')),
            ],
        ),
        migrations.DeleteModel(
            name='LeadPreviewImage',
        ),
    ]
