# Generated by Django 3.2.17 on 2023-11-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0050_delete_extractedlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadpreview',
            name='entry_extraction_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leadpreview',
            name='text_extraction_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='auto_entry_extraction_status',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Pending'), (2, 'Success'), (3, 'Failed')], default=0),
        ),
    ]
