# Generated by Django 3.2.25 on 2024-06-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0050_auto_20240606_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadpreviewattachment',
            name='type',
            field=models.SmallIntegerField(choices=[('1', 'XLSX'), ('2', 'Image')]),
        ),
    ]
