# Generated by Django 3.2.25 on 2024-06-25 05:09

from django.db import migrations, models


def set_file_preview(apps, schema_editor):
    LeadPreviewAttachment = apps.get_model('lead', 'LeadPreviewAttachment')
    LeadPreviewAttachment.objects.update(
        file_preview=models.F('file'),
        type=2,  # default type is Image
    )


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0050_auto_20240621_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadpreviewattachment',
            name='order',
            field=models.IntegerField(default=0)
        ),
        migrations.AddField(
            model_name='leadpreviewattachment',
            name='page_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadpreviewattachment',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'XLSX'), (2, 'Image')], default=1)
        ),
        migrations.RunPython(
            set_file_preview,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='leadpreviewattachment',
            name='file_preview',
            field=models.FileField(upload_to='lead-preview/attachments-preview/')
        ),
    ]
