# Generated by Django 3.2.25 on 2024-06-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0051_alter_leadpreviewattachment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadpreviewattachment',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[('1', 'XLSX'), ('2', 'Image')], default='1'),
        ),
    ]
