# Generated by Django 3.2.17 on 2023-11-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0051_auto_20231128_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadpreview',
            name='entry_extraction_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadpreview',
            name='text_extraction_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
