# Generated by Django 3.2.25 on 2024-06-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0052_alter_leadpreviewattachment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadpreviewattachment',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'XLSX'), (2, 'Image')], default=1),
        ),
    ]
