# Generated by Django 3.2.17 on 2023-11-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0052_auto_20231130_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='auto_entry_extraction_status',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Started'), (2, 'Pending'), (3, 'Success'), (4, 'Failed')], default=0),
        ),
    ]
