# Generated by Django 3.2.17 on 2023-12-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0053_alter_lead_auto_entry_extraction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadpreview',
            name='entry_extraction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadpreview',
            name='text_extraction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
