project = 'Deep Server'
copyright = '2023, DataFriendlySpace'
author = 'DataFriendlySpace'
release = '1.1'
extensions = []
templates_path = ['_templates']
exclude_patterns = []
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
