# Generated by Django 3.2.10 on 2022-03-08 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis_framework', '0036_analysisframeworkrole_type'),
        ('project', '0074_projectrole_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistedTaggingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AssistedTaggingModelPredictionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('tag_id', models.CharField(max_length=256)),
                ('is_depricated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssistedTaggingModelVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=256)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assisted_tagging.assistedtaggingmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AssistedTaggingPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.SmallIntegerField(choices=[(0, 'Raw'), (1, 'Tag')])),
                ('value', models.CharField(blank=True, max_length=255)),
                ('prediction', models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True)),
                ('threshold', models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assisted_tagging.assistedtaggingmodelpredictiontag')),
            ],
        ),
        migrations.CreateModel(
            name='DraftEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excerpt', models.TextField()),
                ('prediction_status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Done'), (3, 'Send Failed')], default=0)),
                ('prediction_received_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draftentry_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WrongPredictionReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wrongpredictionreview_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wrongpredictionreview_modified', to=settings.AUTH_USER_MODEL)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_prediction_reviews', to='assisted_tagging.assistedtaggingprediction')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PredictionTagAnalysisFrameworkWidgetMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association', models.JSONField(default=dict)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assisted_tagging.assistedtaggingmodelpredictiontag')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_framework.widget')),
            ],
        ),
        migrations.CreateModel(
            name='MissingPredictionReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assisted_tagging.assistedtaggingmodelpredictiontag')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missingpredictionreview_created', to=settings.AUTH_USER_MODEL)),
                ('draft_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_prediction_reviews', to='assisted_tagging.draftentry')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missingpredictionreview_modified', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assisted_tagging.assistedtaggingmodelpredictiontag')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assistedtaggingprediction',
            name='draft_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='assisted_tagging.draftentry'),
        ),
        migrations.AddField(
            model_name='assistedtaggingprediction',
            name='model_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assisted_tagging.assistedtaggingmodelversion'),
        ),
        migrations.AddField(
            model_name='assistedtaggingprediction',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assisted_tagging.assistedtaggingmodelpredictiontag'),
        ),
    ]
