# Generated by Django 3.2.10 on 2022-03-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assisted_tagging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistedtaggingmodelpredictiontag',
            old_name='is_depricated',
            new_name='is_deprecated',
        ),
    ]
