# Generated by Django 3.2.10 on 2022-03-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisted_tagging', '0002_rename_is_depricated_assistedtaggingmodelpredictiontag_is_deprecated'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistedtaggingmodelpredictiontag',
            name='hide_in_analysis_framework_mapping',
            field=models.BooleanField(default=False),
        ),
    ]
