# Generated by Django 3.2.10 on 2022-03-08 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0039_lead_connector_lead'),
        ('assisted_tagging', '0003_assistedtaggingmodelpredictiontag_hide_in_analysis_framework_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftentry',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lead.lead'),
            preserve_default=False,
        ),
    ]
