# Generated by Django 3.2.10 on 2022-03-09 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assisted_tagging', '0004_draftentry_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictiontaganalysisframeworkwidgetmapping',
            name='association',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictiontaganalysisframeworkwidgetmapping',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assisted_tagging.assistedtaggingmodelpredictiontag'),
        ),
    ]
