# Generated by Django 3.2.10 on 2022-03-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisted_tagging', '0005_auto_20220309_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistedtaggingprediction',
            name='prediction',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='assistedtaggingprediction',
            name='threshold',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=22, null=True),
        ),
    ]
