# Generated by Django 3.2.10 on 2022-03-09 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assisted_tagging', '0006_auto_20220309_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistedtaggingmodelpredictiontag',
            name='is_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistedtaggingmodelpredictiontag',
            name='parent_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assisted_tagging.assistedtaggingmodelpredictiontag'),
        ),
    ]
