# Generated by Django 3.2.10 on 2022-03-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisted_tagging', '0007_auto_20220309_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistedtaggingmodelpredictiontag',
            name='group',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='assistedtaggingmodelpredictiontag',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
