# Generated by Django 3.2.10 on 2022-03-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisted_tagging', '0008_auto_20220310_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistedtaggingmodelpredictiontag',
            name='group',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
