# Generated by Django 3.2.10 on 2022-04-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0039_region_centroid'),
        ('assisted_tagging', '0009_alter_assistedtaggingmodelpredictiontag_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftentry',
            name='related_geoareas',
            field=models.ManyToManyField(blank=True, to='geo.GeoArea'),
        ),
    ]
