# Generated by Django 3.2.17 on 2023-12-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('assisted_tagging', '0011_draftentry_draft_entry_type'), ('assisted_tagging', '0012_draftentry_is_discarded'), ('assisted_tagging', '0013_rename_draft_entry_type_draftentry_type')]

    dependencies = [
        ('assisted_tagging', '0010_draftentry_related_geoareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftentry',
            name='is_discarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draftentry',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Auto Extraction'), (1, 'Manual Extraction')], default=1),
        ),
    ]
