# Generated by Django 3.2.17 on 2023-12-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisted_tagging', '0011_draftentry_draft_entry_type_squashed_0013_rename_draft_entry_type_draftentry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftentry',
            name='page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draftentry',
            name='text_order',
            field=models.IntegerField(default=0),
        ),
    ]
