# Generated by Django 3.2.25 on 2024-11-28 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assisted_tagging', '0012_auto_20231222_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMAssistedTaggingPredication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('model_tags', models.JSONField(blank=True, null=True)),
                ('draft_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llmpredictions', to='assisted_tagging.draftentry')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assisted_tagging.assistedtaggingmodelversion')),
            ],
        ),
    ]
