# Generated by Django 3.2.17 on 2023-12-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assisted_tagging', '0012_draftentry_is_discarded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftentry',
            old_name='draft_entry_type',
            new_name='type',
        ),
    ]
