# Generated by Django 3.2.12 on 2022-06-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', 'rename_duplicate_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
