# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 11:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170907_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
