# Generated by Django 3.2.17 on 2023-11-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20230508_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_assessment_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
