# Generated by Django 3.2.17 on 2023-12-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_enable_publicly_viewable_analysis_report_snapshot'),
        ('project', 'set_is_assessment_enabled_true'),
    ]

    operations = [
    ]
