# Generated by Django 3.2.17 on 2024-01-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projectpinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpinned',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
