# Generated by Django 3.2.17 on 2024-02-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_merge_20231227_0610'),
        ('project', '0006_projectpinned_modified_at'),
    ]

    operations = [
    ]
