# Generated by Django 3.2.25 on 2024-05-21 04:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0007_merge_20240218_0618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectpinned',
            unique_together={('project', 'user')},
        ),
    ]
