# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_editor', '0001_initial'),
        ('project', '0010_auto_20171129_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category_editor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category_editor.CategoryEditor'),
        ),
    ]
