# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0007_auto_20180223_0643'),
        ('project', '0012_auto_20180216_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assessment_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ary.AssessmentTemplate'),
        ),
    ]
