# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_assessment_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assessment_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ary.AssessmentTemplate'),
        ),
    ]
