# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_project_dummy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='dummy',
            new_name='is_default',
        ),
    ]
