# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-15 07:43
from __future__ import unicode_literals

from django.db import migrations

from project.permissions import get_project_permissions_value


def create_base_roles(apps, schema_editor):
    ProjectRole = apps.get_model('project', 'ProjectRole')
    # Admin Role
    ProjectRole.objects.create(
            title='Admin',
            lead_permissions=get_project_permissions_value('lead', '__all__'),
            entry_permissions=get_project_permissions_value(
                'entry', '__all__'),
            setup_permissions=get_project_permissions_value(
                'setup', '__all__'),
            export_permissions=get_project_permissions_value(
                'export', '__all__'),
            is_creator_role=True
        )
    # Default role
    ProjectRole.objects.create(
        title='Analyst',
        lead_permissions=get_project_permissions_value(
            'lead', '__all__'),
        entry_permissions=get_project_permissions_value(
            'entry', '__all__'),
        setup_permissions=get_project_permissions_value('setup', []),
        export_permissions=get_project_permissions_value(
            'export', ['create']),
        is_default_role=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_projectrole'),
    ]

    operations = [
        migrations.RunPython(create_base_roles),
    ]
