# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-13 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_auto_20180913_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_groups',
            field=models.ManyToManyField(blank=True, through='project.ProjectUserGroupMembership', to='user_group.UserGroup'),
        ),
    ]
