# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-30 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_auto_20180819_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='assessment_permissions',
            field=models.IntegerField(default=0),
        ),
    ]
