# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-30 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_auto_20180913_1116'),
        ('project', '0040_auto_20180902_0709'),
    ]

    operations = [
    ]
