# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-12 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_auto_20181011_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrole',
            options={},
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='projectrole',
            name='modified_by',
        ),
    ]
