# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_projectmembership_is_role_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectusergroupmembership',
            name='role',
            field=models.ForeignKey(default=project.models.get_default_role_id, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectRole'),
        ),
    ]
