# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0012_auto_20180604_0732'),
        ('project', '0047_auto_20181123_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmembership',
            name='is_directly_added',
        ),
        migrations.RemoveField(
            model_name='projectmembership',
            name='is_role_modified',
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='linked_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_group.UserGroup'),
        ),
    ]
