# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_auto_20181123_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='level',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
