# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-27 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_auto_20181127_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatuscondition',
            name='condition_type',
            field=models.CharField(choices=[('some_leads', 'Some leads created since'), ('some_entries', 'Some entries created since'), ('no_leads', 'No leads created since'), ('no_entries', 'No entries created since')], max_length=48),
        ),
    ]
