# Generated by Django 2.1.9 on 2019-07-03 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0055_project_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEntryStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='entry-stats/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=30)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_stats', to='project.Project')),
            ],
        ),
    ]
