# Generated by Django 2.1.11 on 2019-09-12 09:06

from django.db import migrations, models


def forward_create_view_only_unprotected_role(apps, schema_editor):
    ProjectRole = apps.get_model('project', 'ProjectRole')
    ProjectRole.objects.create(
        title='View Only Unprotected',
        lead_permissions=1 << 4,
        entry_permissions=1 << 4,
    )


def backward_remove_view_only_unprotected_role(apps, schema_editor):
    ProjectRole = apps.get_model('project', 'ProjectRole')

    permission_value = 1 << 4  # view_only_unprotected value
    ProjectRole.objects.annotate(
        lead_view_only_permission=models.F('lead_permissions').bitand(permission_value),
        entry_view_only_permission=models.F('entry_permissions').bitand(permission_value)
    ).filter(
        lead_view_only_permission=permission_value,
        entry_view_only_permission=permission_value,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0056_projectentrystats'),
    ]

    operations = [
        migrations.RunPython(
            forward_create_view_only_unprotected_role,
            backward_remove_view_only_unprotected_role,
        ),
    ]
