# Generated by Django 2.1.10 on 2019-11-15 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0057_view_only_unprotected_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAryStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=30)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='ary-stats/')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ary_stats', to='project.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
