# Generated by Django 2.1.8 on 2019-12-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0059_auto_20191202_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_visualization_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
