# Generated by Django 2.1.15 on 2020-04-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0060_project_is_visualization_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectarystats',
            name='confidential_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='entry-stats/'),
        ),
    ]
