# Generated by Django 2.1.15 on 2020-07-15 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20191111_0845'),
        ('project', '0061_projectarystats_confidential_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_type', models.CharField(choices=[('lead_organization', 'Lead Organization'), ('international_partner', 'International Partner'), ('national_partner', 'National Partner'), ('donor', 'Donor'), ('government', 'Government')], max_length=30)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(through='project.ProjectOrganization', to='organization.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='projectorganization',
            unique_together={('project', 'organization_type', 'organization')},
        ),
    ]
