# Generated by Django 2.1.15 on 2020-08-04 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0061_projectarystats_confidential_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=30)),
                ('file', models.FileField(blank=True, max_length=255, null=True, upload_to='project-stats/')),
                ('confidential_file', models.FileField(blank=True, max_length=255, null=True, upload_to='project-stats/')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_stats', to='project.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectarystats',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectentrystats',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectAryStats',
        ),
        migrations.DeleteModel(
            name='ProjectEntryStats',
        ),
    ]
