# Generated by Django 2.1.15 on 2020-07-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0062_auto_20200715_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(blank=True, through='project.ProjectOrganization', to='organization.Organization'),
        ),
    ]
