# Generated by Django 2.1.15 on 2020-09-01 11:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0062_auto_20200804_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjoinrequest',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
