# Generated by Django 2.1.15 on 2020-09-02 04:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import project.models


class Migration(migrations.Migration):

    replaces = [('project', '0063_projectjoinrequest_data'), ('project', '0064_auto_20200902_0438')]

    dependencies = [
        ('project', '0062_auto_20200804_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjoinrequest',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=project.models.get_default_join_request_data, null=True),
        ),
    ]
