# Generated by Django 2.1.15 on 2020-09-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0063_auto_20200715_1131'),
        ('project', '0063_projectjoinrequest_data_squashed_0064_auto_20200902_0438'),
    ]

    operations = [
    ]
