# Generated by Django 2.1.15 on 2021-01-26 10:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0064_merge_20200917_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stats_cache',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
