# Generated by Django 2.1.15 on 2021-03-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0065_project_stats_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstatuscondition',
            name='project_status',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=30),
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
        migrations.DeleteModel(
            name='ProjectStatusCondition',
        ),
    ]
