# Generated by Django 2.1.15 on 2021-03-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0065_project_stats_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstats',
            name='token',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
