# Generated by Django 2.1.15 on 2021-03-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0066_projectstats_token'),
        ('project', '0066_auto_20210319_0843'),
    ]

    operations = [
    ]
