# Generated by Django 2.1.15 on 2021-04-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0066_projectstats_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstatuscondition',
            name='project_status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
        migrations.DeleteModel(
            name='ProjectStatusCondition',
        ),
    ]
