# Generated by Django 2.1.15 on 2021-04-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0068_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstats',
            name='public_share',
            field=models.BooleanField(default=False),
        ),
    ]
