# Generated by Django 3.2 on 2021-06-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0067_auto_20210503_0431'),
        ('project', '0069_projectstats_public_share'),
    ]

    operations = [
    ]
