# Generated by Django 2.1.15 on 2021-04-29 04:17

import django.contrib.postgres.fields
from django.db import migrations
import django_enumfield.db.fields
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0069_projectstats_public_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='badges',
            field=django.contrib.postgres.fields.ArrayField(base_field=django_enumfield.db.fields.EnumField(enum=project.models.ProjectMembership.BadgeType), blank=True, default=list, size=None),
        ),
    ]
