# Generated by Django 2.1.15 on 2021-04-29 09:50

import django.contrib.postgres.fields
from django.db import migrations
import django.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0070_projectmembership_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectusergroupmembership',
            name='badges',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.db.models.IntegerField(choices=[(0, 'Quality Assurance')]), blank=True, default=list, size=None),
        ),
    ]
