# Generated by Django 3.2 on 2021-08-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0070_merge_20210603_0624'),
        ('project', '0071_projectusergroupmembership_badges'),
    ]

    operations = [
    ]
