# Generated by Django 3.2.10 on 2022-01-14 05:09

from django.db import migrations, models


def initial_project_test_set(apps, schema_editor):
    Project = apps.get_model('project', 'Project')
    projects_qs = Project.objects.filter(title__icontains='test')
    projects_qs.update(is_test=True)

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0074_projectrole_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            initial_project_test_set,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
