# Generated by Django 3.2.12 on 2022-05-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0075_project_has_publicly_viewable_leads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='has_publicly_viewable_leads',
            new_name='has_publicly_viewable_unprotected_leads',
        ),
        migrations.AddField(
            model_name='project',
            name='has_publicly_viewable_confidential_leads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='has_publicly_viewable_restricted_leads',
            field=models.BooleanField(default=False),
        ),
    ]
