# Generated by Django 3.2.12 on 2022-05-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0075_project_has_publicly_viewable_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='geo_cache_file',
            field=models.FileField(blank=True, null=True, upload_to='project-geo-cache/'),
        ),
        migrations.AddField(
            model_name='project',
            name='geo_cache_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
