# Generated by Django 3.2.12 on 2022-05-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0076_auto_20220520_0834'),
        ('project', '0076_auto_20220524_0523'),
    ]

    operations = [
    ]
