# Generated by Django 3.2.10 on 2022-06-24 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0078_auto_20220601_0815'),
        ('project', 'rename_duplicate_project_name'),
    ]

    operations = [
    ]
