# Generated by Django 3.2.12 on 2022-06-24 06:40

from django.db import migrations


def _set_istest_true_for_test_projects(Project):
    Project.objects.filter(title__icontains='test').update(is_test=True)


def set_istest_true_for_test_projects(apps, schema_editor):
    Project = apps.get_model('project', 'Project')
    _set_istest_true_for_test_projects(Project)


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_project_is_test'),
    ]

    operations = [
        migrations.RunPython(
            set_istest_true_for_test_projects,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
