# Generated by Django 2.1.15 on 2020-10-14 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20201013_0829'),
        ('notification', '0005_auto_20200930_0652'),
    ]

    operations = [
    ]
