# Generated by Django 2.1.15 on 2021-01-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
