# Generated by Django 3.2 on 2021-08-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_alter_notification_data'),
        ('notification', '0007_auto_20210427_0507'),
    ]

    operations = [
    ]
