# Generated by Django 3.2.15 on 2023-01-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_projectchangelog'),
        ('geo', '0040_region_cache_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Entries Count By Geo Area')], unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntriesCountByGeoAreaAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entries_count', models.IntegerField()),
                ('geo_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.geoarea')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'ordering': ('date',),
                'unique_together': {('project', 'geo_area', 'date')},
            },
        ),
    ]
