# Generated by Django 3.2.17 on 2023-02-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_explore', '0002_publicexploreyearsnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicexploreyearsnapshot',
            options={'ordering': ('year',)},
        ),
        migrations.AddField(
            model_name='publicexploreyearsnapshot',
            name='download_file',
            field=models.FileField(blank=True, max_length=255, upload_to='deep-explore/public-excel-export/'),
        ),
    ]
