# Generated by Django 3.2.17 on 2023-02-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_explore', '0003_auto_20230217_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicExploreSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'Global Snapshot'), (2, 'Yearly Snapshot')])),
                ('global_type', models.SmallIntegerField(choices=[(1, 'Full Dataset'), (2, 'Time Series Dataset')], null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('year', models.SmallIntegerField(null=True, unique=True)),
                ('file', models.FileField(max_length=255, upload_to='deep-explore/public-snapshot/')),
                ('download_file', models.FileField(blank=True, max_length=255, upload_to='deep-explore/public-excel-export/')),
            ],
            options={
                'ordering': ('type', 'year'),
            },
        ),
        migrations.DeleteModel(
            name='PublicExploreYearSnapshot',
        ),
    ]
