# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20170921_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-modified_at', '-created_at']},
        ),
    ]
