# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0002_auto_20171006_0746'),
        ('project', '0005_auto_20171004_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='analysis_framework',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis_framework.AnalysisFramework'),
        ),
    ]
