# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 06:01
from __future__ import unicode_literals

from django.db import migrations


def add_analysis_frameworks(apps, schema_editor):
    Project = apps.get_model('project', 'Project')
    AnalysisFramework = apps.get_model('analysis_framework', 'AnalysisFramework')

    for project in Project.objects.all():
        if not project.analysis_framework:
            analysis_framework = AnalysisFramework(title=project.title)
            analysis_framework.save()
            project.analysis_framework = analysis_framework
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20171121_0804'),
    ]

    operations = [
        migrations.RunPython(add_analysis_frameworks),
    ]
