# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20180308_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
    ]
