# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-05 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20180604_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('and_conditions', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatusCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('no_leads', 'No leads created since'), ('no_entries', 'No entries created since')], max_length=48)),
                ('value', models.IntegerField()),
                ('project_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectStatus')),
            ],
        ),
    ]
