# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-07 12:09
from __future__ import unicode_literals

from django.db import migrations

from project.models import Project


def migrate_project_status(apps, schema_editor):
    for project in Project.objects.all():
        project.status = project.calc_status()
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_project_status'),
    ]

    operations = [
        migrations.RunPython(migrate_project_status),
    ]
