# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-13 10:50
from __future__ import unicode_literals

from django.db import migrations

def from_old_user_groups_to_new_user_groups(apps, schema_editor):
    Project = apps.get_model('project', 'Project')
    ProjectUserGroupMembership = apps.get_model(
        'project',
        'ProjectUserGroupMembership'
    )
    for each in Project.user_groups.through.objects.all():
        ProjectUserGroupMembership.objects.create(
            project=each.project,
            usergroup=each.usergroup,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_auto_20180913_1050'),
    ]

    operations = [
            migrations.RunPython(from_old_user_groups_to_new_user_groups),
    ]
