# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-15 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_auto_20180815_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjoinrequest',
            name='newrole',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='newrole',
            field=models.IntegerField(default=0),
        ),
    ]
