# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-13 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_auto_20180913_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user_groups',
        ),
    ]
