# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-13 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_remove_project_user_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_group_new',
            new_name='user_groups',
        ),
    ]
