# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-15 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_auto_20180815_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectjoinrequest',
            name='newrole',
        ),
        migrations.RemoveField(
            model_name='projectmembership',
            name='newrole',
        ),
        migrations.AddField(
            model_name='projectjoinrequest',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectRole'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectRole'),
        ),
    ]
