# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-15 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_auto_20180815_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectjoinrequest',
            old_name='newrole',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='projectmembership',
            old_name='newrole',
            new_name='role',
        ),
    ]
