# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-15 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_auto_20180815_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectrole',
            old_name='excerpt_permissions',
            new_name='entry_permissions',
        ),
    ]
