# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-19 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_auto_20180815_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectjoinrequest',
            name='role',
        ),
        migrations.RemoveField(
            model_name='projectmembership',
            name='role',
        ),
    ]
