# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-19 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_auto_20180819_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjoinrequest',
            name='role',
            field=models.CharField(choices=[('normal', 'Normal'), ('admin', 'Admin')], default='normal', max_length=96),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(choices=[('normal', 'Normal'), ('admin', 'Admin')], default='normal', max_length=96),
        ),
    ]
