# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-19 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_auto_20180819_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjoinrequest',
            name='newrole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectRole'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='newrole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectRole'),
        ),
    ]
