# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-19 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_auto_20180819_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectjoinrequest',
            name='role',
        ),
        migrations.RemoveField(
            model_name='projectmembership',
            name='role',
        ),
    ]
