# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-11 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0012_auto_20180604_0732'),
        ('project', '0041_merge_20180930_0624'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectusergroupmembership',
            unique_together=set([('usergroup', 'project')]),
        ),
    ]
