# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-19 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_auto_20180819_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectjoinrequest',
            old_name='newrole',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='projectmembership',
            old_name='newrole',
            new_name='role',
        ),
    ]
