# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-11 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_auto_20181011_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.ForeignKey(default=project.models.get_default_role_id, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectRole'),
        ),
    ]
