# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-23 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_auto_20181012_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='is_role_modified',
            field=models.BooleanField(default=False),
        ),
    ]
