# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-06 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en-us', 'English (US)'), ('np', 'Nepali')], default='en-us', max_length=255)),
                ('key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en-us', 'English (US)'), ('np', 'Nepali')], default='en-us', max_length=255)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang.String'),
        ),
    ]
