# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-19 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0002_auto_20180506_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='string',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lang.String'),
        ),
    ]
