# Generated by Django 2.1.15 on 2020-02-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0003_auto_20180519_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='language',
            field=models.CharField(choices=[('en-us', 'English (US)'), ('es-ES', 'Spanish'), ('np', 'Nepali')], default='en-us', max_length=255),
        ),
        migrations.AlterField(
            model_name='string',
            name='language',
            field=models.CharField(choices=[('en-us', 'English (US)'), ('es-ES', 'Spanish'), ('np', 'Nepali')], default='en-us', max_length=255),
        ),
    ]
