# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 08:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_filepreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepreview',
            name='file',
        ),
        migrations.AddField(
            model_name='filepreview',
            name='file_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
