# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20171230_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filepreview',
            old_name='text_extract',
            new_name='text',
        ),
    ]
