# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20171230_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created_at']},
        ),
    ]
