# Generated by Django 2.1.7 on 2019-03-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_file_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='random_string',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
