# Generated by Django 2.1.10 on 2019-08-02 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_file_random_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='random_string',
        ),
        migrations.AddField(
            model_name='file',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
