# Generated by Django 2.1.10 on 2019-08-02 09:12

import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    FileModel = apps.get_model('gallery', 'File')
    for file in FileModel.objects.all():
        file.uuid = uuid.uuid4()
        file.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_add_uuid_20190802_0902'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
