# Generated by Django 3.2 on 2021-06-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_auto_20210120_0443'),
        ('gallery', '0019_auto_20210503_0431'),
    ]

    operations = [
    ]
