# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0004_auto_20180223_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodologyfield',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.MethodologyGroup'),
        ),
    ]
