# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0005_auto_20180223_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatafield',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='ary.MetadataGroup'),
        ),
        migrations.AlterField(
            model_name='metadataoption',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ary.MetadataField'),
        ),
        migrations.AlterField(
            model_name='methodologyfield',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='ary.MethodologyGroup'),
        ),
        migrations.AlterField(
            model_name='methodologyoption',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ary.MethodologyField'),
        ),
    ]
