# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0006_auto_20180223_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectedgroup',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ary.AffectedGroup'),
        ),
    ]
