# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0007_auto_20180223_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lead.Lead'),
        ),
    ]
