# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 07:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0008_auto_20180312_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PriorityIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ary.PriorityIssue')),
            ],
            options={
                'abstract': False,
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PrioritySector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ary.PrioritySector')),
            ],
            options={
                'abstract': False,
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SepecificNeedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='summary_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='humanitarian_access_constraints_tooltip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='humanitarian_affected_location_tooltip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='humanitarian_limited_tooltip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='humanitarian_priority_issue_tooltip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='humanitarian_restricted_tooltip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='sector_affected_tooltip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='sector_moderate_pin_tooltip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='sector_pin_tooltip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='sector_priority_tooltip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='sector_severe_pin_tooltip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessmenttemplate',
            name='sector_specific_need_tooltip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sepecificneedgroup',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.AssessmentTemplate'),
        ),
        migrations.AddField(
            model_name='prioritysector',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.AssessmentTemplate'),
        ),
        migrations.AddField(
            model_name='priorityissue',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.AssessmentTemplate'),
        ),
        migrations.AddField(
            model_name='focus',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.AssessmentTemplate'),
        ),
        migrations.AddField(
            model_name='affectedlocation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.AssessmentTemplate'),
        ),
    ]
