# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0013_auto_20180405_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='summary_data',
            new_name='summary',
        ),
    ]
