# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-18 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0015_auto_20180417_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scorescale',
            old_name='title',
            new_name='color',
        ),
        migrations.AlterField(
            model_name='scorematrixcolumn',
            name='pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='ary.ScoreMatrixPillar'),
        ),
        migrations.AlterField(
            model_name='scorematrixrow',
            name='pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ary.ScoreMatrixPillar'),
        ),
        migrations.AlterField(
            model_name='scorematrixscale',
            name='pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='ary.ScoreMatrixPillar'),
        ),
        migrations.AlterField(
            model_name='scorequestion',
            name='pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ary.ScorePillar'),
        ),
    ]
