# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-18 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0016_auto_20180418_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorematrixscale',
            name='order',
        ),
        migrations.RemoveField(
            model_name='scorematrixscale',
            name='title',
        ),
    ]
