# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-19 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0014_auto_20180416_0944'),
        ('ary', '0017_auto_20180418_1056'),
    ]

    operations = [
    ]
