# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 05:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0019_auto_20180419_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='score',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
