# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-27 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0021_auto_20180420_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(default=0)),
                ('max_value', models.FloatField(default=5)),
                ('score', models.FloatField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ary.AssessmentTemplate')),
            ],
            options={
                'ordering': ['min_value'],
            },
        ),
    ]
