# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ary', '0023_auto_20180507_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatafield',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'Multiselect'), ('countries', 'Countries'), ('organizations', 'Organizations')], default='string', max_length=50),
        ),
        migrations.AlterField(
            model_name='methodologyfield',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'Multiselect'), ('countries', 'Countries'), ('organizations', 'Organizations')], default='string', max_length=50),
        ),
    ]
