# Generated by Django 2.1.8 on 2020-01-05 07:47

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0060_project_is_visualization_enabled'),
        ('analysis_framework', '0028_auto_20190802_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrameworkQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('enumerator_instruction', models.TextField(blank=True)),
                ('respondent_instruction', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, choices=[('text', 'Text'), ('number', 'Number'), ('date_and_time', 'Date and time'), ('select', 'Select'), ('rank', 'Rank'), ('location', 'Location'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('file_upload', 'File upload'), ('barcode', 'Barcode'), ('range', 'Range')], max_length=56)),
                ('importance', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=56)),
                ('framework_attribute', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('data_collection_technique', models.CharField(blank=True, choices=[('direct', 'Direct')], max_length=56)),
                ('enumerator_skill', models.CharField(blank=True, choices=[('basic', 'Basic'), ('medium', 'Medium')], max_length=56)),
                ('analysis_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_framework.AnalysisFramework')),
                ('crisis_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.CrisisType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('enumerator_instruction', models.TextField(blank=True)),
                ('respondent_instruction', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, choices=[('text', 'Text'), ('number', 'Number'), ('date_and_time', 'Date and time'), ('select', 'Select'), ('rank', 'Rank'), ('location', 'Location'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('file_upload', 'File upload'), ('barcode', 'Barcode'), ('range', 'Range')], max_length=56)),
                ('importance', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=56)),
                ('framework_attribute', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('data_collection_technique', models.CharField(blank=True, choices=[('direct', 'Direct')], max_length=56)),
                ('enumerator_skill', models.CharField(blank=True, choices=[('basic', 'Basic'), ('medium', 'Medium')], max_length=56)),
                ('analysis_framework', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis_framework.AnalysisFramework')),
                ('cloned_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.FrameworkQuestion')),
                ('crisis_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.CrisisType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, default=None, max_length=128, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
                ('data_collection_technique', models.CharField(blank=True, choices=[('direct', 'Direct')], max_length=56)),
                ('enumerator_skill', models.CharField(blank=True, choices=[('basic', 'Basic'), ('medium', 'Medium')], max_length=56)),
                ('required_duration', models.PositiveIntegerField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_created', to=settings.AUTH_USER_MODEL)),
                ('crisis_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.CrisisType')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire'),
        ),
    ]
