# Generated by Django 2.1.15 on 2020-02-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('questionnaire', '0003_question_is_archived'), ('questionnaire', '0004_auto_20200205_1438'), ('questionnaire', '0005_auto_20200207_0556'), ('questionnaire', '0006_auto_20200207_0601'), ('questionnaire', '0007_auto_20200207_0602'), ('questionnaire', '0008_frameworkquestion_is_archived'), ('questionnaire', '0009_auto_20200211_0832'), ('questionnaire', '0010_auto_20200217_0748')]

    dependencies = [
        ('questionnaire', '0002_auto_20200114_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frameworkquestion',
            name='required_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='required_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frameworkquestion',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='frameworkquestion',
            name='type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('date', 'Date'), ('time', 'Time'), ('dateTime', 'Date and time'), ('select_one', 'Select one'), ('select_multiple', 'Select multiple'), ('rank', 'Rank'), ('geopoint', 'Geopoint'), ('geotrace', 'Geotrace'), ('geoshape', 'Geoshape'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('file', 'Generic File'), ('barcode', 'Barcode'), ('range', 'Range')], max_length=56),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('date', 'Date'), ('time', 'Time'), ('dateTime', 'Date and time'), ('select_one', 'Select one'), ('select_multiple', 'Select multiple'), ('rank', 'Rank'), ('geopoint', 'Geopoint'), ('geotrace', 'Geotrace'), ('geoshape', 'Geoshape'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('file', 'Generic File'), ('barcode', 'Barcode'), ('range', 'Range')], max_length=56),
        ),
        migrations.AddField(
            model_name='frameworkquestion',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frameworkquestion',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='required_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='frameworkquestion',
            name='label',
        ),
        migrations.RemoveField(
            model_name='question',
            name='label',
        ),
    ]
