# Generated by Django 2.1.15 on 2020-05-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20200519_0915'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('questionnaire', 'name')},
        ),
    ]
