# Generated by Django 3.2 on 2021-05-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20200519_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworkquestion',
            name='framework_attribute',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='frameworkquestion',
            name='response_options',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='framework_attribute',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='response_options',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
