# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0006_auto_20171122_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
