# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0009_usergroup_display_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('normal', 'Normal'), ('admin', 'Admin')], default='normal', max_length=96),
        ),
    ]
