# Generated by Django 2.1.15 on 2021-06-21 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_group', '0012_auto_20180604_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='usergroup',
            name='client_id',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergroup',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usergroup_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usergroup_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
