# Generated by Django 3.2 on 2021-05-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0012_auto_20180604_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='custom_project_fields',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
