# Generated by Django 3.2 on 2021-06-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0013_alter_usergroup_custom_project_fields'),
        ('user_group', '0013_auto_20210621_1515'),
    ]

    operations = [
    ]
