# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_group', '0003_auto_20171114_1112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together=set([('member', 'group')]),
        ),
    ]
