# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0005_usergroup_project_specific_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='project_specific_fields',
            new_name='custom_project_fields',
        ),
    ]
