# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20171230_0858'),
        ('user_group', '0008_remove_usergroup_display_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='display_picture',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.File'),
        ),
    ]
