# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-04 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_group', '0010_auto_20180410_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='added_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_group_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
