# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 06:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('name_property', models.CharField(blank=True, max_length=225)),
                ('pcode_property', models.CharField(blank=True, max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='GeoArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.CharField(blank=True, max_length=225)),
                ('pcode', models.CharField(blank=True, max_length=225)),
                ('admin_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.AdminLevel')),
            ],
        ),
        migrations.CreateModel(
            name='GeoShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='adminlevel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Country'),
        ),
        migrations.AddField(
            model_name='adminlevel',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.AdminLevel'),
        ),
        migrations.AddField(
            model_name='adminlevel',
            name='shape',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.GeoShape'),
        ),
    ]
