# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlevel',
            name='name_property',
        ),
        migrations.RemoveField(
            model_name='adminlevel',
            name='pcode_property',
        ),
        migrations.AddField(
            model_name='adminlevel',
            name='name_prop',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adminlevel',
            name='parent_name_prop',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adminlevel',
            name='parent_pcode_prop',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adminlevel',
            name='pcode_prop',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='geoarea',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.GeoArea'),
        ),
        migrations.AlterField(
            model_name='adminlevel',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='geoarea',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='geoarea',
            name='pcode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='geoarea',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
