# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 09:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20170907_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('is_global', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='adminlevel',
            name='country',
        ),
        migrations.AlterField(
            model_name='adminlevel',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.AdminLevel'),
        ),
        migrations.AlterField(
            model_name='geoarea',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.GeoArea'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddField(
            model_name='adminlevel',
            name='region',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='geo.Region'),
            preserve_default=False,
        ),
    ]
