# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_remove_geoarea_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='is_global',
            new_name='public',
        ),
    ]
