# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0012_auto_20171013_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['title', 'code']},
        ),
    ]
