# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 09:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0016_auto_20171210_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoarea',
            name='polygons',
        ),
        migrations.AddField(
            model_name='adminlevel',
            name='polygons',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
