# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0020_adminlevel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlevel',
            name='stale_geo_areas',
            field=models.BooleanField(default=False),
        ),
    ]
