# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0022_auto_20171218_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlevel',
            name='tolerance',
            field=models.FloatField(default=0.0001),
        ),
    ]
