# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 10:29
from __future__ import unicode_literals

from django.db import migrations
from geo.models import GeoArea


def migrate_labels(apps, schema):
    for g in GeoArea.objects.all():
        g.save()


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0027_auto_20180325_0739'),
    ]

    operations = [
        migrations.RunPython(migrate_labels),
    ]
