# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0031_adminlevel_geo_area_titles'),
        ('geo', '0029_region_client_id'),
    ]

    operations = [
    ]
