# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-27 07:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0012_filter_widget_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportable',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='exportable',
            old_name='key',
            new_name='widget_key',
        ),
        migrations.AddField(
            model_name='exportable',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='exportable',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
