# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0014_auto_20180107_0538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['title', 'widget_key', 'key']},
        ),
    ]
