# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-14 10:14
from __future__ import unicode_literals

from django.db import migrations
from analysis_framework.utils import update_widgets


def update_matrix1d(apps, schema_editor):
    update_widgets('matrix1dWidget')


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0016_auto_20180216_0931'),
    ]

    operations = [
        migrations.RunPython(update_matrix1d),
    ]
