# Generated by Django 2.1.8 on 2019-06-25 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis_framework', '0019_auto_20181031_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFrameworkMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisFrameworkRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('can_add_user', models.BooleanField(default=False)),
                ('can_clone_framework', models.BooleanField(default=False)),
                ('can_make_public', models.BooleanField(default=False)),
                ('can_edit_framework', models.BooleanField(default=False)),
                ('can_use_in_other_projects', models.BooleanField(default=False)),
                ('is_default_role', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='analysisframework',
            name='snapshot_one',
        ),
        migrations.RemoveField(
            model_name='analysisframework',
            name='snapshot_two',
        ),
        migrations.AddField(
            model_name='analysisframework',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='analysisframeworkrole',
            unique_together={('can_add_user', 'can_clone_framework', 'can_make_public', 'can_edit_framework', 'can_use_in_other_projects', 'is_default_role')},
        ),
        migrations.AddField(
            model_name='analysisframeworkmembership',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_framework.AnalysisFramework'),
        ),
        migrations.AddField(
            model_name='analysisframeworkmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisframeworkmembership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_framework.AnalysisFrameworkRole'),
        ),
        migrations.AddField(
            model_name='analysisframework',
            name='members',
            field=models.ManyToManyField(blank=True, through='analysis_framework.AnalysisFrameworkMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='analysisframeworkmembership',
            unique_together={('member', 'framework')},
        ),
    ]
