# Generated by Django 2.1.8 on 2019-06-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0020_auto_20190621_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisframework',
            name='snapshot_one',
        ),
        migrations.RemoveField(
            model_name='analysisframework',
            name='snapshot_two',
        ),
    ]
