# Generated by Django 2.1.9 on 2019-07-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0021_auto_20190711_0625'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analysisframeworkrole',
            unique_together={('can_add_user', 'can_clone_framework', 'can_edit_framework', 'can_use_in_other_projects', 'is_default_role')},
        ),
    ]
