# Generated by Django 2.1.9 on 2019-07-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0022_auto_20190711_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisframeworkrole',
            name='can_make_public',
        ),
    ]
