# Generated by Django 2.1.9 on 2019-07-12 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0023_remove_analysisframeworkrole_can_make_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisframeworkmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
