# Generated by Django 2.1.10 on 2019-07-18 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0025_analysisframeworkrole_is_private_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analysisframeworkrole',
            unique_together={('can_add_user', 'can_clone_framework', 'can_edit_framework', 'is_private_role', 'can_use_in_other_projects', 'is_default_role')},
        ),
    ]
