# Generated by Django 2.1.9 on 2019-07-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0026_analysisframework_properties'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analysisframeworkrole',
            unique_together={('can_add_user', 'can_clone_framework', 'can_edit_framework', 'can_use_in_other_projects', 'is_default_role', 'is_private_role')},
        ),
    ]
