# Generated by Django 2.1.10 on 2019-07-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0026_auto_20190718_0504'),
        ('analysis_framework', '0020_analysisframework_properties'),
    ]

    operations = [
    ]
