# Generated by Django 2.1.9 on 2019-08-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0027_auto_20190726_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisframework',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
