# Generated by Django 2.1.15 on 2020-01-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0028_auto_20190802_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='filter_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('list', 'List'), ('intersects', 'Intersection between two numbers')], default='list', max_length=20),
        ),
    ]
