# Generated by Django 2.1.8 on 2019-12-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0028_auto_20190802_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('enumerator_instruction', models.TextField()),
                ('respondent_instruction', models.TextField()),
                ('type', models.CharField(max_length=56)),
                ('importance', models.CharField(max_length=56)),
                ('selected_framework_attribute_type', models.CharField(max_length=56)),
                ('selected_framework_attribute_value', models.CharField(max_length=56)),
                ('analysis_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_framework.AnalysisFramework')),
            ],
        ),
    ]
