# Generated by Django 2.1.8 on 2019-12-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0029_frameworkquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frameworkquestion',
            name='selected_framework_attribute_type',
        ),
        migrations.RemoveField(
            model_name='frameworkquestion',
            name='selected_framework_attribute_value',
        ),
        migrations.AddField(
            model_name='frameworkquestion',
            name='framework_attribute_type',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AddField(
            model_name='frameworkquestion',
            name='framework_attribute_value',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='frameworkquestion',
            name='enumerator_instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='frameworkquestion',
            name='importance',
            field=models.CharField(blank=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='frameworkquestion',
            name='respondent_instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='frameworkquestion',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='frameworkquestion',
            name='type',
            field=models.CharField(blank=True, max_length=56),
        ),
    ]
