# Generated by Django 2.1.15 on 2021-05-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_organizationtype_short_name'),
        ('analysis_framework', '0029_auto_20200117_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisframework',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='analysisframework',
            name='preview_image',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='af-preview-image/'),
        ),
    ]
