# Generated by Django 2.1.8 on 2019-12-25 14:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0030_auto_20191225_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frameworkquestion',
            name='framework_attribute_type',
        ),
        migrations.RemoveField(
            model_name='frameworkquestion',
            name='framework_attribute_value',
        ),
        migrations.AddField(
            model_name='frameworkquestion',
            name='framework_attribute',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
