# Generated by Django 3.2 on 2021-06-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0030_auto_20210503_0431'),
        ('analysis_framework', '0030_auto_20210506_1055'),
    ]

    operations = [
    ]
