# Generated by Django 3.2.5 on 2021-07-29 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0031_merge_0030_auto_20210503_0431_0030_auto_20210506_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_id',
            field=models.CharField(choices=[('dateWidget', 'Date'), ('dateRangeWidget', 'Date Range'), ('timeWidget', 'Time'), ('timeRangeWidget', 'Time Range'), ('numberWidget', 'Number'), ('scaleWidget', 'Scale'), ('geoWidget', 'Geo'), ('selectWidget', 'Select'), ('multiselectWidget', 'Multiselect'), ('organigramWidget', 'Organigram'), ('matrix1dWidget', 'Matrix1D'), ('matrix2dWidget', 'Matrix2D'), ('numberMatrixWidget', 'Number Matrix'), ('conditionalWidget', 'Conditional'), ('textWidget', 'Text'), ('excerptWidget', 'Excerpt #DEPRICATED')], db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('analysis_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis_framework.analysisframework')),
            ],
        ),
        migrations.AddField(
            model_name='widget',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis_framework.section'),
        ),
    ]
