# Generated by Django 3.2.5 on 2021-08-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0032_auto_20210730_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='width',
            field=models.CharField(choices=[('full', 'Full'), ('half', 'Half')], default='full', max_length=10),
        ),
        migrations.AlterField(
            model_name='section',
            name='tooltip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
