# Generated by Django 3.2.5 on 2021-11-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0033_auto_20210817_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='version',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
