# Generated by Django 3.2.9 on 2021-12-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0035_auto_20211130_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisframeworkrole',
            name='type',
            field=models.CharField(choices=[('editor', 'Editor'), ('owner', 'Owner'), ('default', 'default'), ('private_editor', 'Private Editor'), ('private_owner', 'Private Owner'), ('private_viewer', 'Private Viewer'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
    ]
