# Generated by Django 3.2.10 on 2022-03-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0036_analysisframeworkrole_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisframework',
            name='assisted_tagging_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
