# Generated by Django 3.2.17 on 2023-05-17 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0038_analysisframework_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisframework',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis_framework.analysisframework'),
        ),
    ]
