# Generated by Django 3.2.17 on 2023-11-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0039_analysisframework_cloned_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFrameworkTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.FileField(max_length=255, upload_to='af-tag-icon/')),
            ],
        ),
        migrations.AddField(
            model_name='analysisframework',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='_analysis_framework_analysisframework_tags_+', to='analysis_framework.AnalysisFrameworkTag'),
        ),
    ]
