# Generated by Django 3.2.17 on 2024-02-22 05:02

from django.db import migrations,transaction

@transaction.atomic
def analysis_framework_widgets_mapping(apps, schema_editor):
    AnalysisFramework = apps.get_model('analysis_framework', 'AnalysisFramework')
    analysis_framework_data = AnalysisFramework.objects.filter(properties__isnull=False)
    for af in analysis_framework_data:
        if af.properties != {}:
            widget_properties = af.properties
            widget_properties['stats_config']['widget_1d'] = widget_properties['stats_config'].get('widget1d') or widget_properties['stats_config'].get('widget_1d') or []  # noqa
            widget_properties['stats_config']['widget_2d'] = widget_properties['stats_config'].get('widget2d') or widget_properties['stats_config'].get('widget_2d') or []  # noqa
            widget_properties['stats_config']['organigram_widgets'] = widget_properties['stats_config'].get('affected_groups_widgets') or widget_properties['stats_config'].get('organigram_widgets') or widget_properties['stats_config'].get('organigram_widget') or []  # noqa
            widget_properties['stats_config']['multiselect_widgets'] = widget_properties['stats_config'].get('specific_needs_groups_widgets') or widget_properties['stats_config'].get('multiselect_widgets') or widget_properties['stats_config'].get('multiselect_widget') or []  # noqa
            if 'old_stats_config' in widget_properties:
                widget_properties.pop('old_stats_config')
            remove_key = ['widget2d', 'widget1d', 'affected_groups_widgets', 'specific_needs_groups_widgets', 'affected_groups_widget', 'specific_needs_groups_widget']  # noqa
            for widget_key in list(widget_properties['stats_config'].keys()):
                if widget_key in remove_key:
                    del widget_properties['stats_config'][widget_key]
            af.properties = widget_properties
            af.save()


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_framework', '0040_auto_20231109_1208'),
    ]
    operations = [
        migrations.RunPython(
            analysis_framework_widgets_mapping,
            reverse_code=migrations.RunPython.noop
        )
    ]
