# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 11:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_auto_20170921_0753'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('confidentiality', models.CharField(choices=[('unprotected', 'Unprotected'), ('protected', 'Protected'), ('restricted', 'Restricted'), ('confidential', 'Confidential')], default='unprotected', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('deleted', 'Deleted')], default='pending', max_length=30)),
                ('published_on', models.DateField(blank=True, default=None, null=True)),
                ('text', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('attachment', models.FileField(blank=True, default=None, null=True, upload_to='lead_attachments/%Y/%m/')),
                ('assignee', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
