# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_auto_20171004_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='attachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to='lead-attachments/%Y/%m/'),
        ),
    ]
