# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_auto_20171016_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadPreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_extract', models.TextField(blank=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lead.Lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadPreviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lead-preview/')),
                ('lead_preview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.LeadPreview')),
            ],
        ),
    ]
