# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_leadpreview_leadpreviewimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadpreviewimage',
            name='lead_preview',
        ),
        migrations.AddField(
            model_name='leadpreviewimage',
            name='lead',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lead.Lead'),
            preserve_default=False,
        ),
    ]
