# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_auto_20171104_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source_type',
            field=models.CharField(choices=[('text', 'Text'), ('disk', 'Disk'), ('website', 'Website'), ('dropbox', 'Dropbox'), ('google-drive', 'Google Drive'), ('unknown', 'Unknown')], default='unknown', max_length=30),
        ),
    ]
