# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_lead_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='classified_doc_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
