# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-02 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0011_auto_20171221_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadpreviewimage',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lead.Lead'),
        ),
    ]
