# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0013_auto_20180107_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='url',
            field=models.TextField(),
        ),
    ]
