# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-10 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0016_auto_20180216_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source_type',
            field=models.CharField(choices=[('text', 'Text'), ('disk', 'Disk'), ('website', 'Website'), ('dropbox', 'Dropbox'), ('google-drive', 'Google Drive'), ('rss', 'RSS Feed'), ('api', 'Web API'), ('unknown', 'Unknown')], default='unknown', max_length=30),
        ),
    ]
