# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-05 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0019_auto_20180713_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='file_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='size_in_bytes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
