# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-05 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0020_auto_20181005_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='file_type',
            new_name='mime_type',
        ),
    ]
