# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-28 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0020_auto_20180925_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadpreview',
            name='thumbnail_height',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='leadpreview',
            name='thumbnail_width',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leadpreview',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, height_field='thumbnail_height', null=True, upload_to='lead-thumbnail/', width_field='thumbnail_width'),
        ),
    ]
