# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-05 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0021_auto_20181005_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='mime_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
