# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0021_auto_20181228_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='tabular_book',
        ),
    ]
