# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-05 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0022_remove_lead_tabular_book'),
        ('lead', '0022_merge_20190110_0605'),
    ]

    operations = [
    ]
