# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hid',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
