# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 08:51
from __future__ import unicode_literals

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20171016_1028'),
    ]

    operations = [
        CreateExtension('pg_trgm'),
        CreateExtension('postgis'),
    ]
