# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_category_editor'),
        ('user', '0005_auto_20180107_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_active_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
