# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_login_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_active_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project'),
        ),
    ]
