# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 05:59
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20180802_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_opt_outs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('join_requests', 'Project join requests'), ('news_and_updates', 'News and updates')], max_length=128), blank=True, default=[], size=None),
        ),
    ]
