# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-30 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20181120_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experimental',
            field=models.BooleanField(default=False),
        ),
    ]
