# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_profile_experimental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='experimental',
            new_name='is_experimental',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_early_access',
            field=models.BooleanField(default=False),
        ),
    ]
