# Generated by Django 3.2.10 on 2022-03-01 13:22

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0010_organizationtype_short_name'),
        ('project', '0074_projectrole_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('published_on', models.DateField(blank=True, default=None, null=True)),
                ('source_raw', models.CharField(blank=True, max_length=255)),
                ('authors_raw', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('extraction_status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (4, 'Retrying'), (2, 'Success'), (3, 'Failed')], default=0)),
                ('authors', models.ManyToManyField(blank=True, related_name='_unified_connector_connectorlead_authors_+', to='organization.Organization')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('atom-feed', 'Atom Feed'), ('relief-web', 'Relifweb'), ('rss-feed', 'RSS Feed'), ('unhcr-portal', 'UNHCR Portal')], max_length=20)),
                ('params', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connectorsource_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connectorsource_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnifiedConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unifiedconnector_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unifiedconnector_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectorSourceLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.BooleanField(default=False)),
                ('already_added', models.BooleanField(default=False)),
                ('connector_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unified_connector.connectorlead')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unified_connector.connectorsource')),
            ],
        ),
        migrations.AddField(
            model_name='connectorsource',
            name='unified_connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='unified_connector.unifiedconnector'),
        ),
        migrations.AlterUniqueTogether(
            name='connectorsource',
            unique_together={('unified_connector', 'source')},
        ),
    ]
