# Generated by Django 3.2.10 on 2022-03-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unified_connector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectorsource',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='connectorlead',
            name='authors_raw',
        ),
        migrations.AddField(
            model_name='connectorlead',
            name='author_raw',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='connectorlead',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectorlead',
            name='simplified_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='connectorlead',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectorsource',
            name='last_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectorsource',
            name='leads',
            field=models.ManyToManyField(blank=True, through='unified_connector.ConnectorSourceLead', to='unified_connector.ConnectorLead'),
        ),
        migrations.AddField(
            model_name='connectorsource',
            name='stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='connectorsource',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Processing'), (2, 'success'), (3, 'failure')], default=0),
        ),
        migrations.AlterField(
            model_name='connectorlead',
            name='extraction_status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Retrying'), (2, 'Started'), (3, 'Success'), (4, 'Failed')], default=0),
        ),
        migrations.AlterField(
            model_name='connectorlead',
            name='url',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='connectorsourcelead',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_leads', to='unified_connector.connectorsource'),
        ),
        migrations.AlterUniqueTogether(
            name='connectorsource',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ConnectorLeadPreviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=255, upload_to='connector-lead/preview-images/')),
                ('connector_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unified_connector.connectorlead')),
            ],
        ),
    ]
