# Generated by Django 3.2.10 on 2022-03-04 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unified_connector', '0002_auto_20220303_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectorleadpreviewimage',
            name='connector_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_images', to='unified_connector.connectorlead'),
        ),
    ]
