# Generated by Django 3.2.10 on 2022-03-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_connector', '0003_alter_connectorleadpreviewimage_connector_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorlead',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
