# Generated by Django 3.2.10 on 2022-04-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_connector', '0004_connectorlead_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorsource',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectorsource',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
