# Generated by Django 3.2.17 on 2023-12-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_connector', '0007_alter_connectorsource_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorlead',
            name='text_extraction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
