# Generated by Django 3.2.25 on 2024-06-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unified_connector', '0008_connectorlead_text_extraction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorLeadPreviewAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('page_number', models.IntegerField(default=0)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'XLSX'), (2, 'Image')], default=1)),
                ('file', models.FileField(upload_to='connector-lead/attachments/')),
                ('file_preview', models.FileField(upload_to='connector-lead/attachments-preview/')),
                ('connector_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_images', to='unified_connector.connectorlead')),
            ],
        ),
        migrations.DeleteModel(
            name='ConnectorLeadPreviewImage',
        ),
    ]
