# Generated by Django 3.2.25 on 2024-06-25 08:06

from django.db import migrations, models


def set_file_preview(apps, schema_editor):
    ConnectorLeadPreviewAttachment = apps.get_model('unified_connector', 'ConnectorLeadPreviewAttachment')
    ConnectorLeadPreviewAttachment.objects.update(
        file_preview=models.F('file'),
        type=2,  # default type is image
    )


class Migration(migrations.Migration):

    dependencies = [
        ('unified_connector', '0009_auto_20240621_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorleadpreviewattachment',
            name='order',
            field=models.IntegerField(default=0)
        ),
        migrations.AddField(
            model_name='connectorleadpreviewattachment',
            name='page_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='connectorleadpreviewattachment',
            name='file_preview',
            field=models.FileField(upload_to='connector-lead/attachments-preview/')
        ),
        migrations.AddField(
            model_name='connectorleadpreviewattachment',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'XLSX'), (2, 'Image')], default=1)
        ),
        migrations.RunPython(
            set_file_preview,
            reverse_code=migrations.RunPython.noop,
        )
    ]
