# Generated by Django 3.2.25 on 2024-10-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_connector', '0010_auto_20240625_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectorsource',
            name='source',
            field=models.CharField(choices=[('atom-feed', 'Atom Feed'), ('relief-web', 'Relifweb'), ('rss-feed', 'RSS Feed'), ('unhcr-portal', 'UNHCR Portal'), ('humanitarian-resp', 'Humanitarian Response'), ('pdna', 'Post Disaster Needs Assessments'), ('emm', 'European Media Monitor'), ('kobo', 'KoboToolbox')], max_length=20),
        ),
    ]
