# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep_migration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminlevelmigration',
            options={'ordering': ['-first_migrated_at']},
        ),
        migrations.AlterModelOptions(
            name='countrymigration',
            options={'ordering': ['-first_migrated_at']},
        ),
        migrations.RenameField(
            model_name='adminlevelmigration',
            old_name='migrated_at',
            new_name='first_migrated_at',
        ),
        migrations.RenameField(
            model_name='countrymigration',
            old_name='migrated_at',
            new_name='first_migrated_at',
        ),
        migrations.AddField(
            model_name='adminlevelmigration',
            name='last_migrated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='countrymigration',
            name='last_migrated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
