# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deep_migration', '0002_auto_20180114_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlevelmigration',
            name='admin_level',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.AdminLevel'),
        ),
        migrations.AlterField(
            model_name='countrymigration',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Region'),
        ),
    ]
