# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 08:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deep_migration', '0003_auto_20180114_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminlevelmigration',
            old_name='level',
            new_name='old_id',
        ),
    ]
