# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deep_migration', '0006_usermigration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermigration',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
