# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_auto_20180102_0457'),
        ('deep_migration', '0011_auto_20180115_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_migrated_at', models.DateTimeField(auto_now_add=True)),
                ('last_migrated_at', models.DateTimeField(auto_now=True)),
                ('old_id', models.IntegerField(unique=True)),
                ('entry', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.Entry')),
            ],
            options={
                'ordering': ['-first_migrated_at'],
                'abstract': False,
            },
        ),
    ]
