# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deep_migration', '0012_entrymigration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrymigration',
            name='entry',
        ),
        migrations.DeleteModel(
            name='EntryMigration',
        ),
    ]
