# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-28 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0007_usergroup_description'),
        ('deep_migration', '0013_auto_20180121_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_migrated_at', models.DateTimeField(auto_now_add=True)),
                ('last_migrated_at', models.DateTimeField(auto_now=True)),
                ('old_id', models.IntegerField(unique=True)),
                ('user_group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_group.UserGroup')),
            ],
            options={
                'ordering': ['-first_migrated_at'],
                'abstract': False,
            },
        ),
    ]
