# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20170907_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
