# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20170920_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminlevel',
            old_name='parent_pcode_prop',
            new_name='code_prop',
        ),
        migrations.RenameField(
            model_name='adminlevel',
            old_name='pcode_prop',
            new_name='parent_code_prop',
        ),
        migrations.RenameField(
            model_name='geoarea',
            old_name='pcode',
            new_name='code',
        ),
    ]
