# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 06:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0014_auto_20171121_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlevel',
            name='geo_shape',
        ),
        migrations.AddField(
            model_name='adminlevel',
            name='geo_shape_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='shape_files/'),
        ),
        migrations.AddField(
            model_name='geoarea',
            name='polygons',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
