# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 09:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0018_auto_20171210_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlevel',
            name='polygons',
        ),
        migrations.AddField(
            model_name='geoarea',
            name='polygons',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, null=True, srid=4326),
        ),
    ]
