# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0019_auto_20171210_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlevel',
            name='level',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
