# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0021_adminlevel_stale_geo_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlevel',
            name='stale_geo_areas',
            field=models.BooleanField(default=True),
        ),
    ]
