# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 07:39
from __future__ import unicode_literals

from django.db import migrations, models


def resave_areas(apps, schema_editor):
    GeoArea = apps.get_model('geo', 'GeoArea')
    for geo_area in GeoArea.objects.all():
        geo_area.save()


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0026_auto_20180228_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarea',
            name='long_label',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='geoarea',
            name='short_label',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(resave_areas),
    ]
