# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-30 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0027_auto_20180325_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoarea',
            name='long_label',
        ),
        migrations.RemoveField(
            model_name='geoarea',
            name='short_label',
        ),
    ]
