# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-12 10:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0028_auto_20180330_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlevel',
            name='bounds',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='adminlevel',
            name='geojson',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='geo_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
