# Generated by Django 2.1.8 on 2019-04-29 06:24

from django.db import migrations


def clear_region_geo_options_cache(apps, schema_editor):
    Region = apps.get_model('geo', 'Region')

    Region.objects.all().update(geo_options=None)


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0033_auto_20190429_0541'),
    ]

    operations = [
        migrations.RunPython(clear_region_geo_options_cache),
    ]
