# Generated by Django 2.1.10 on 2019-07-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0035_auto_20190730_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlevel',
            name='bounds',
        ),
        migrations.RemoveField(
            model_name='adminlevel',
            name='geojson',
        ),
    ]
