# Generated by Django 3.2 on 2021-07-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0037_auto_20210503_0431'),
    ]

    operations = [
        # Set is_published to True for current regions
        migrations.AddField(
            model_name='region',
            name='is_published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        # Set is_published to False for new regions by default.
        migrations.AlterField(
            model_name='region',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
