# Generated by Django 3.2 on 2021-06-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0037_auto_20210503_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
