# Generated by Django 3.2.5 on 2021-10-25 08:00

from django.contrib.gis.db.models.aggregates import Union as PgUnion
from django.contrib.gis.db.models.functions import Centroid
import django.contrib.gis.db.models.fields
from django.contrib.gis.db import models
from django.db import migrations


def recalculate_region_cache(apps, schema_editor):
    Region = apps.get_model('geo', 'Region')
    GeoArea = apps.get_model('geo', 'GeoArea')
    Region.objects.update(
        centroid=models.Subquery(
            GeoArea.objects.filter(
                admin_level__region=models.OuterRef('pk')
            ).values('admin_level__region').order_by().annotate(
                centroid=Centroid(PgUnion(Centroid('polygons'))),
            ).values('centroid')[:1],
            output_field=models.PointField(),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0038_auto_20210702_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.RunPython(
            recalculate_region_cache,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
