# Generated by Django 3.2 on 2021-06-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0038_region_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
