# Generated by Django 3.2.12 on 2022-05-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0039_region_centroid'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='cache_index',
            field=models.SmallIntegerField(default=0),
        ),
    ]
