# Generated by Django 3.2.17 on 2023-08-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0041_geoarea_centroid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoarea',
            old_name='data',
            new_name='cached_data',
        ),
    ]
