# Generated by Django 3.2.25 on 2024-12-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0043_create-unaccent_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Initiated'), (1, 'Pending'), (2, 'Completed'), (3, 'Failed')], default=1),
        ),
    ]
