# Generated by Django 3.2.25 on 2024-10-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0043_create-unaccent_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
    ]
