# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_auto_20180102_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='information_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
