# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_entry_information_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('excerpt', 'Excerpt'), ('image', 'Image')], default='excerpt', max_length=10),
        ),
    ]
