# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0013_auto_20180824_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterdata',
            name='number_from',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='filterdata',
            name='number_to',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
