# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0017_field_cache'),
        ('entry', '0016_merge_20181120_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='data_series',
        ),
        migrations.AddField(
            model_name='entry',
            name='tabular_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tabular.Field'),
        ),
    ]
