# Generated by Django 2.1.8 on 2019-05-07 05:07

from django.db import migrations

from entry.utils import update_attributes


def update_number_matrix_attributes(apps, schema_editor):
    """
    NOTE: This migration is out-of-date. Keeping it here for reference only.
    
    update_attributes(widget__widget_id='numberMatrixWidget')
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0017_auto_20190306_0617'),
    ]

    operations = [
        migrations.RunPython(update_number_matrix_attributes),
    ]
