# Generated by Django 2.1.9 on 2019-07-03 10:45

from django.db import migrations
from entry.utils import update_attributes


def update_entry_attributes(apps, schema_editor):
    update_attributes(widget__widget_id__in=['scaleWidget', 'organigramWidget'])


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0018_auto_20190507_0507'),
    ]

    operations = [
        migrations.RunPython(update_entry_attributes),
    ]
