# Generated by Django 2.1.10 on 2019-12-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0020_entrycomment_entrycommenttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='dropped_excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='highlight_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
