# Generated by Django 2.1.15 on 2020-01-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0022_auto_20200110_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterdata',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
