# Generated by Django 2.1.15 on 2020-06-30 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0023_filterdata_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrycomment',
            name='assignees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entrycomment',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee_entrycomment', to=settings.AUTH_USER_MODEL),
        ),
    ]
