# Generated by Django 2.1.15 on 2020-06-30 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0025_entry-comment-assignee-to-assignees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrycomment',
            name='assignee',
        ),
    ]
