# Generated by Django 2.1.15 on 2020-09-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0026_remove_entrycomment_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
