# Generated by Django 2.1.15 on 2020-09-11 07:25

from django.db import migrations


def update_attributes(apps, schema_editor):
    Attribute = apps.get_model('entry', 'Attribute')
    for each in Attribute.objects.all():
        each.save()


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0026_remove_entrycomment_assignee'),
    ]

    operations = [
        migrations.RunPython(update_attributes)
    ]
