# Generated by Django 2.1.15 on 2021-03-01 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0028_auto_20200914_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='approved_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
