# Generated by Django 3.2 on 2021-05-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0028_auto_20200914_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exportdata',
            name='data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
