# Generated by Django 3.2 on 2021-06-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0029_auto_20210112_0935'),
        ('entry', '0029_auto_20210503_0431'),
    ]

    operations = [
    ]
