# Generated by Django 2.1.15 on 2021-04-27 10:08

from django.db import migrations, models

from deep.managers import BulkCreateManager
from quality_assurance.models import CommentType


# NOTE: Using _ here as importlib doesn't find private functions
def migrate_entry_controlled_to_review_comment_(Entry, EntryReviewComment):
    # We can create review comment if controlled_changed_by is available.
    # NOTE: At this state controlled_changed_by has data verified_changed_by
    entry_qs = Entry.objects.filter(
        controlled_changed_by__isnull=False,
    )

    bulk_mgr = BulkCreateManager(chunk_size=5000)
    for entry_id, controlled, controlled_changed_by_id in (
        entry_qs.values_list('id', 'controlled', 'controlled_changed_by_id').iterator(chunk_size=10000)
    ):
        bulk_mgr.add(
            EntryReviewComment(
                entry_id=entry_id,
                created_by_id=controlled_changed_by_id,
                comment_type=CommentType.VERIFY if controlled else CommentType.UNVERIFY,
            )
        )
        if controlled:
            bulk_mgr.add(
                Entry.verified_by.through(
                    entry_id=entry_id,
                    user_id=controlled_changed_by_id,
                )
            )
    bulk_mgr.done()
    # Reset all Entry controlled status
    Entry.objects.update(controlled=False, controlled_changed_by=None)


def migrate_entry_controlled_to_review_comment(apps, schema_editor):
    Entry = apps.get_model('entry', 'Entry')
    EntryReviewComment = apps.get_model('quality_assurance', 'EntryReviewComment')
    migrate_entry_controlled_to_review_comment_(Entry, EntryReviewComment)


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0030_auto_20210427_0507'),
        ('quality_assurance', '0002_entryreviewcomment_created_at'),
    ]

    operations = [
        migrations.RunPython(
            migrate_entry_controlled_to_review_comment,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
