# Generated by Django 2.1.15 on 2021-05-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0029_auto_20210112_0935'),
        ('entry', '0031_entry-migrate-verify-to-review-comment'),
    ]

    operations = [
    ]
