# Generated by Django 3.2 on 2021-08-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0030_merge_0029_auto_20210112_0935_0029_auto_20210503_0431'),
        ('entry', '0032_merge_20210506_0840'),
    ]

    operations = [
    ]
