# Generated by Django 3.2.5 on 2021-11-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0033_merge_20210805_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='widget_version',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
