# Generated by Django 3.2.10 on 2022-04-01 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0036_entry_draft_entry'),
        ('entry', '0036_entry_excerpt_modified'),
    ]

    operations = [
    ]
