# Generated by Django 3.2.25 on 2024-06-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0037_merge_20220401_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('excerpt', 'Excerpt'), ('image', 'Image'), ('attachment', 'Attachment'), ('dataSeries', 'Data Series')], default='excerpt', max_length=10),
        ),
        migrations.CreateModel(
            name='EntryAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_file_type', models.PositiveSmallIntegerField(choices=[('1', 'XLSX')], default='1')),
                ('file', models.FileField(upload_to='entry/attachment/')),
                ('file_preview', models.FileField(upload_to='entry/attachment-preview')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entry.entry')),
            ],
        ),
    ]
