# Generated by Django 3.2.25 on 2024-06-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0038_auto_20240609_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryattachment',
            name='entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.entryattachment'),
        ),
    ]
