# Generated by Django 3.2.25 on 2024-06-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0039_auto_20240609_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryattachment',
            name='entry_file_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'XLSX')], default=1),
        ),
    ]
