# Generated by Django 3.2.25 on 2024-06-11 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0053_alter_leadpreviewattachment_type'),
        ('entry', '0040_alter_entryattachment_entry_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryattachment',
            name='lead_attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.leadpreviewattachment'),
        ),
        migrations.AlterField(
            model_name='entryattachment',
            name='entry_file_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'XLSX'), (2, 'Image')], default=1),
        ),
    ]
