# Generated by Django 2.1.15 on 2021-02-26 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import quality_assurance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entry', '0028_auto_20200914_1146'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryReviewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', django_enumfield.db.fields.EnumField(default=0, enum=quality_assurance.models.CommentType)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entryreviewcomment_created', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Entry')),
                ('mentioned_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntryReviewCommentText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_texts', to='quality_assurance.EntryReviewComment')),
            ],
            options={
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
    ]
