# Generated by Django 2.1.15 on 2021-03-15 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quality_assurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryreviewcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
