# Generated by Django 3.2.12 on 2022-06-02 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0037_merge_20220401_0527'),
        ('quality_assurance', '0004_entry_comment_to_qa_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryreviewcomment',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='entry.entry'),
        ),
    ]
