name: Graphql Inspector Runner

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'develop:schema.graphql'
          approve-label: 'approved-breaking-change'
