# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresource',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userresource',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='UserResource',
        ),
    ]
